import { PublicClientApplication, InteractionRequiredAuthError } from '@azure/msal-browser';
const DEFAULT_CLIENT_ID='ab342dfc-cab4-45f3-acdb-3e49d606f418';
const clientId=import.meta.env.VITE_ENTRA_CLIENT_ID||DEFAULT_CLIENT_ID;
const authority=import.meta.env.VITE_ENTRA_AUTHORITY||'https://login.microsoftonline.com/organizations';
export const AUTH_CONFIGURED=Boolean(clientId);
export const CORE_SCOPES=['User.Read','User.Read.All','Application.Read.All','Group.Read.All','Device.Read.All','AuditLog.Read.All'];
export const SECURITY_SCOPES=['IdentityRiskyUser.Read.All','RoleManagement.Read.Directory','Policy.Read.All'];
export const LICENSE_SCOPES=['Organization.Read.All'];
export const GRAPH_SCOPES=CORE_SCOPES;
let msalInstance;let initPromise;let redirectResult;
function getMsal(){if(!AUTH_CONFIGURED)return null;if(!msalInstance)msalInstance=new PublicClientApplication({auth:{clientId,authority,redirectUri:window.location.origin,postLogoutRedirectUri:window.location.origin},cache:{cacheLocation:'sessionStorage',storeAuthStateInCookie:false}});if(!initPromise)initPromise=msalInstance.initialize();return msalInstance;}
export async function initializeAuth(){const instance=getMsal();if(!instance)return null;await initPromise;redirectResult=await instance.handleRedirectPromise();if(redirectResult?.account)instance.setActiveAccount(redirectResult.account);const accounts=instance.getAllAccounts();if(accounts.length&&!instance.getActiveAccount())instance.setActiveAccount(accounts[0]);return instance.getActiveAccount()||accounts[0]||null;}
export async function signIn(){const instance=getMsal();if(!instance)throw new Error('Microsoft Entra authentication is not configured.');await initPromise;await instance.loginRedirect({scopes:['User.Read'],redirectStartPage:window.location.href});}
async function acquireToken(scopes,allowRedirect=true){const instance=getMsal();if(!instance)throw new Error('Microsoft Entra authentication is not configured.');await initPromise;const account=instance.getActiveAccount()||instance.getAllAccounts()[0];if(!account)throw new Error('Sign in before connecting a tenant.');try{return await instance.acquireTokenSilent({account,scopes});}catch(error){if(error instanceof InteractionRequiredAuthError&&allowRedirect){await instance.acquireTokenRedirect({account,scopes,redirectStartPage:window.location.href});return null;}throw error;}}
export async function connectTenant(){const result=await acquireToken(CORE_SCOPES,true);return result?{account:result.account,accessToken:result.accessToken,scopes:result.scopes}:null;}
export async function connectSecurityScopes(){const result=await acquireToken(SECURITY_SCOPES,true);return result?{account:result.account,accessToken:result.accessToken,scopes:result.scopes}:null;}
export async function connectLicenseScopes(){const result=await acquireToken(LICENSE_SCOPES,true);return result?{account:result.account,accessToken:result.accessToken,scopes:result.scopes}:null;}
export async function getGraphToken(scopes=CORE_SCOPES,allowRedirect=true){const result=await acquireToken(scopes,allowRedirect);return result?.accessToken||null;}
export async function graphGet(path,scopes=CORE_SCOPES,version='v1.0',allowRedirect=true){const token=await getGraphToken(scopes,allowRedirect);if(!token)throw new Error('Microsoft authentication redirect in progress.');const response=await fetch(`https://graph.microsoft.com/${version}${path}`,{headers:{Authorization:`Bearer ${token}`,Accept:'application/json',ConsistencyLevel:'eventual'}});if(!response.ok){const body=await response.text();const error=new Error(`Microsoft Graph ${response.status}: ${body}`);error.status=response.status;throw error;}return response.json();}
export async function graphGetOptional(path,scopes,version='v1.0'){try{return{ok:true,data:await graphGet(path,scopes,version,false)};}catch(error){return{ok:false,error};}}
async function dailySignIns(days=7){const now=new Date();const requests=[];for(let i=days-1;i>=0;i--){const start=new Date(now);start.setHours(0,0,0,0);start.setDate(start.getDate()-i);const end=new Date(start);end.setDate(end.getDate()+1);const filter=`createdDateTime ge ${start.toISOString()} and createdDateTime lt ${end.toISOString()}`;requests.push(graphGet(`/auditLogs/signIns?$count=true&$top=1&$filter=${encodeURIComponent(filter)}`,CORE_SCOPES));}const results=await Promise.allSettled(requests);return results.map((r,i)=>{const d=new Date(now);d.setHours(0,0,0,0);d.setDate(d.getDate()-(days-1-i));return{date:d.toISOString().slice(0,10),total:r.status==='fulfilled'?Number(r.value['@odata.count']||0):null};});}
function lastActivity(item){const values=[item.lastSignInActivity?.lastSignInDateTime,item.applicationAuthenticationClientSignInActivity?.lastSignInDateTime,item.applicationAuthenticationResourceSignInActivity?.lastSignInDateTime,item.delegatedClientSignInActivity?.lastSignInDateTime,item.delegatedResourceSignInActivity?.lastSignInDateTime].filter(Boolean).map(x=>new Date(x).getTime());return values.length?Math.max(...values):0;}
function computeCredentialExpiry(apps){const now=Date.now();const items=[];for(const app of apps){const creds=[...(app.keyCredentials||[]).map(c=>({type:'certificate',endDateTime:c.endDateTime})),...(app.passwordCredentials||[]).map(c=>({type:'secret',endDateTime:c.endDateTime}))];for(const c of creds){if(!c.endDateTime)continue;const daysRemaining=Math.floor((new Date(c.endDateTime).getTime()-now)/86400000);items.push({name:app.displayName||app.appId||'Unnamed application',appId:app.appId,type:c.type,daysRemaining,expiresAt:c.endDateTime});}}items.sort((a,b)=>a.daysRemaining-b.daysRemaining);return items;}
// IMPORTANT: `items` here must already be scoped to the tenant's own registered
// applications (matched by appId). /reports/servicePrincipalSignInActivities
// returns every service principal in the directory, including hundreds of
// Microsoft first-party ones (Graph, Exchange Online, Teams, ...) that were
// never part of "Total Applications" - bucketing the unfiltered report against
// that smaller count produced bucket totals and percentages far above 100%.
function bucketAppActivity(ownApps,activityRecords){const now=Date.now();const cutoff=d=>now-d*86400000;const activityByAppId=new Map((activityRecords||[]).map(a=>[a.appId,a]));const buckets={active30:0,inactive31to90:0,inactive91to180:0,inactive180:0};const inactiveApps=[];const all=[];for(const app of ownApps){const activity=activityByAppId.get(app.appId);const ts=activity?lastActivity(activity):0;const name=app.displayName||app.appId||'Unnamed application';const days=ts?Math.floor((now-ts)/86400000):null;let bucket;if(!ts||ts<cutoff(180)){buckets.inactive180++;bucket='180+';inactiveApps.push({name,appId:app.appId,days});}else if(ts<cutoff(90)){buckets.inactive91to180++;bucket='91-180';inactiveApps.push({name,appId:app.appId,days});}else if(ts<cutoff(30)){buckets.inactive31to90++;bucket='31-90';inactiveApps.push({name,appId:app.appId,days});}else{buckets.active30++;bucket='active';}all.push({name,appId:app.appId,days,bucket});}inactiveApps.sort((a,b)=>(b.days??99999)-(a.days??99999));all.sort((a,b)=>(b.days??99999)-(a.days??99999));return{buckets,inactiveApps:inactiveApps.slice(0,25),all};}
export async function getTenantSnapshot(){
 const collectedAt=new Date().toISOString();const sevenDaysAgo=new Date(Date.now()-7*86400000).toISOString();const permissions=CORE_SCOPES.map(name=>({name,status:'granted',detail:'Requested by core dashboard token'}));
 const core=await Promise.allSettled([graphGet('/organization?$select=id,displayName,verifiedDomains'),graphGet('/applications?$count=true&$top=1'),graphGet('/users?$count=true&$top=1'),graphGet('/groups?$count=true&$top=1'),graphGet('/devices?$count=true&$top=1'),graphGet(`/auditLogs/signIns?$count=true&$top=1&$filter=${encodeURIComponent(`createdDateTime ge ${sevenDaysAgo}`)}`),graphGet(`/auditLogs/signIns?$count=true&$top=1&$filter=${encodeURIComponent(`createdDateTime ge ${sevenDaysAgo} and riskLevelAggregated ne 'none'`)}`),graphGet('/auditLogs/signIns?$top=50&$orderby=createdDateTime desc'),graphGet('/reports/authenticationMethods/userRegistrationDetails?$top=999'),graphGet('/users?$top=999&$select=id,displayName,userPrincipalName,accountEnabled,signInActivity'),graphGet('/users?$top=999&$select=id,displayName,userPrincipalName,accountEnabled&$expand=manager($select=id,displayName,userPrincipalName)'),graphGet('/devices?$top=999&$select=id,displayName,operatingSystem,operatingSystemVersion,trustType,isCompliant,accountEnabled,approximateLastSignInDateTime')]);
 const val=(i,f)=>core[i]?.status==='fulfilled'?core[i].value:f;const org=val(0,{value:[]})?.value?.[0]||{};const applications=val(1,{})?.['@odata.count']??null;const users=val(2,{})?.['@odata.count']??null;const groups=val(3,{})?.['@odata.count']??null;const devices=val(4,{})?.['@odata.count']??null;const signIns7d=val(5,{})?.['@odata.count']??null;const riskySignIns7d=val(6,{})?.['@odata.count']??null;const recentSignIns=val(7,{})?.value||[];const registration=val(8,{})?.value||[];const userActivityRecords=val(9,{})?.value||[];const managerRecords=val(10,{})?.value||[];const deviceRecords=val(11,{})?.value||[];
 const reasonForIndex=i=>core[i]?.status==='rejected'?String(core[i].reason?.message||core[i].reason):null;
 const appCredentials=await graphGetOptional('/applications?$top=999&$select=id,appId,displayName,keyCredentials,passwordCredentials',CORE_SCOPES);const ownApps=appCredentials.ok?(appCredentials.data.value||[]):[];const credentialExpiryItems=appCredentials.ok?computeCredentialExpiry(ownApps):[];
 const activityResult=await graphGetOptional('/reports/servicePrincipalSignInActivities?$top=999',CORE_SCOPES,'beta');const appActivityAvailable=activityResult.ok&&appCredentials.ok;const appActivity=appActivityAvailable?bucketAppActivity(ownApps,activityResult.data.value||[]):{buckets:null,inactiveApps:[]};
 const registrationAvailable=core[8]?.status==='fulfilled';const userActivityAvailable=core[9]?.status==='fulfilled';const managerAvailable=core[10]?.status==='fulfilled';const mfaRegistered=registrationAvailable?registration.filter(u=>u.isMfaRegistered).length:null;const mfaMissing=registrationAvailable?registration.filter(u=>!u.isMfaRegistered).length:null;const mfaMissingUsers=registrationAvailable?registration.filter(u=>!u.isMfaRegistered).map(u=>({id:u.id,name:u.userDisplayName||u.userPrincipalName,upn:u.userPrincipalName})):[];const staleCutoff=Date.now()-90*86400000;const staleUserList=userActivityAvailable?userActivityRecords.filter(u=>u.accountEnabled!==false&&(!u.signInActivity?.lastSignInDateTime||new Date(u.signInActivity.lastSignInDateTime).getTime()<staleCutoff)):[];const staleUsers=userActivityAvailable?staleUserList.length:null;const usersWithoutManager=managerAvailable?managerRecords.filter(u=>u.accountEnabled!==false&&!u.manager).length:null;const userActivityList=userActivityAvailable?userActivityRecords.map(u=>({id:u.id,name:u.displayName||u.userPrincipalName,upn:u.userPrincipalName,enabled:u.accountEnabled,lastSignIn:u.signInActivity?.lastSignInDateTime||null})):[];
 const securityRisk=await graphGetOptional('/identityProtection/riskyUsers?$top=999',SECURITY_SCOPES);const roleAssignments=await graphGetOptional('/roleManagement/directory/roleAssignments?$top=999',SECURITY_SCOPES);const roleDefinitions=await graphGetOptional('/roleManagement/directory/roleDefinitions?$top=999&$filter=isBuiltIn eq true',SECURITY_SCOPES);const conditionalAccess=await graphGetOptional('/identity/conditionalAccess/policies?$top=999',SECURITY_SCOPES);const riskyUserList=securityRisk.ok?(securityRisk.data.value||[]):[];const assignments=roleAssignments.ok?(roleAssignments.data.value||[]):[];const definitions=roleDefinitions.ok?(roleDefinitions.data.value||[]):[];const privilegedRoleIds=new Set(definitions.filter(r=>/administrator|global reader|security reader|privileged role/i.test(r.displayName||'')).map(r=>r.id));const privilegedPrincipalIds=roleAssignments.ok?new Set(assignments.filter(a=>privilegedRoleIds.has(a.roleDefinitionId)).map(a=>a.principalId)):new Set();const privilegedUsers=roleAssignments.ok?privilegedPrincipalIds.size:null;
 // Toxic combinations: cross-reference signals we already collected by AAD object id
 // rather than presenting them as five unrelated counts. "Global Admin with no MFA"
 // is one row an executive can act on; "66 users lack MFA" in the abstract is not.
 const nameById=new Map();for(const u of managerRecords)nameById.set(u.id,u.displayName||u.userPrincipalName);for(const u of userActivityRecords)if(!nameById.has(u.id))nameById.set(u.id,u.displayName||u.userPrincipalName);for(const u of registration)if(!nameById.has(u.id))nameById.set(u.id,u.userDisplayName||u.userPrincipalName);
 const mfaMissingIds=new Set(mfaMissingUsers.map(u=>u.id));const riskyIds=new Set(riskyUserList.map(u=>u.id));const staleIds=new Set(staleUserList.map(u=>u.id));
 const toxicCombinations=[];for(const id of privilegedPrincipalIds){const flags=[];if(registrationAvailable&&mfaMissingIds.has(id))flags.push('No MFA');if(securityRisk.ok&&riskyIds.has(id))flags.push('Risky sign-in (ID Protection)');if(userActivityAvailable&&staleIds.has(id))flags.push('Stale 90+ days');if(flags.length)toxicCombinations.push({id,name:nameById.get(id)||id,flags});}toxicCombinations.sort((a,b)=>b.flags.length-a.flags.length);
 const toxicCombinationsAvailable=roleAssignments.ok&&(registrationAvailable||securityRisk.ok||userActivityAvailable);
 permissions.push({name:'IdentityRiskyUser.Read.All',status:securityRisk.ok?'granted':'missing',detail:securityRisk.ok?'Validated by live Graph request':String(securityRisk.error?.message||'Consent, role, or Entra ID P2 license required')});permissions.push({name:'RoleManagement.Read.Directory',status:roleAssignments.ok?'granted':'missing',detail:roleAssignments.ok?'Validated by live Graph request':String(roleAssignments.error?.message||'Consent or role required')});permissions.push({name:'Policy.Read.All',status:conditionalAccess.ok?'granted':'missing',detail:conditionalAccess.ok?'Validated by live Graph request':String(conditionalAccess.error?.message||'Consent or role required')});
 const signInTrend=await dailySignIns(7);const failed=await graphGetOptional(`/auditLogs/signIns?$count=true&$top=1&$filter=${encodeURIComponent(`createdDateTime ge ${sevenDaysAgo} and status/errorCode ne 0`)}`,CORE_SCOPES);const healthInputs={mfaCoverage:registrationAvailable&&users?mfaRegistered/users:null,riskyUserRate:securityRisk.ok&&users?riskyUserList.length/users:null,inactiveAppRate:appActivityAvailable&&ownApps.length?(appActivity.buckets.inactive91to180+appActivity.buckets.inactive180)/ownApps.length:null,staleUserRate:userActivityAvailable&&users?staleUsers/users:null};const scoreContributors=[];if(healthInputs.mfaCoverage!=null)scoreContributors.push({key:'mfaCoverage',label:'MFA coverage',score:healthInputs.mfaCoverage*100,weightNote:`${fmtPct(healthInputs.mfaCoverage)} of users have MFA registered`});if(healthInputs.riskyUserRate!=null)scoreContributors.push({key:'riskyUserRate',label:'Risky users',score:Math.max(0,100-healthInputs.riskyUserRate*1000),weightNote:`${riskyUserList.length} of ${users} users flagged risky`});if(healthInputs.inactiveAppRate!=null)scoreContributors.push({key:'inactiveAppRate',label:'Application hygiene',score:Math.max(0,100-healthInputs.inactiveAppRate*100),weightNote:`${appActivity.buckets.inactive91to180+appActivity.buckets.inactive180} of ${ownApps.length} apps inactive 90+ days`});if(healthInputs.staleUserRate!=null)scoreContributors.push({key:'staleUserRate',label:'Stale accounts',score:Math.max(0,100-healthInputs.staleUserRate*100),weightNote:`${staleUsers} of ${users} enabled users stale 90+ days`});const healthScore=scoreContributors.length?Math.round(scoreContributors.reduce((a,c)=>a+c.score,0)/scoreContributors.length):null;const excludedSignals=[healthInputs.mfaCoverage==null&&'MFA coverage (permission required)',healthInputs.riskyUserRate==null&&'Risky users (permission/license required)',healthInputs.inactiveAppRate==null&&'Application hygiene (beta report unavailable)',healthInputs.staleUserRate==null&&'Stale accounts (permission required)'].filter(Boolean);
 return {source:'entra',organization:{id:org.id||'',displayName:org.displayName||'',verifiedDomains:org.verifiedDomains||[]},applications,users,groups,devices,signIns7d,riskySignIns7d,appActivity:appActivity.buckets,appPopulation:ownApps.length,inactiveApps:appActivity.inactiveApps,appDetails:appActivity.all,appActivityAvailable,appActivityReason:appActivityAvailable?null:String((activityResult.error||appCredentials.error)?.message||'Unavailable'),recentSignIns,signInTrend,signInsAvailable:core[5]?.status==='fulfilled',signInsReason:reasonForIndex(5)||reasonForIndex(7),failedSignIns7d:failed.ok?Number(failed.data['@odata.count']||0):null,mfa:{registered:mfaRegistered,missing:mfaMissing,observed:registrationAvailable?registration.length:null,missingUsers:mfaMissingUsers},staleUsers,staleUserList:staleUserList.map(u=>({id:u.id,name:u.displayName||u.userPrincipalName,upn:u.userPrincipalName,lastSignIn:u.signInActivity?.lastSignInDateTime||null})),userActivityAvailable,userActivityList,usersWithoutManager,toxicCombinations,toxicCombinationsAvailable,toxicCombinationsCount:toxicCombinations.length,riskyUsers:securityRisk.ok?riskyUserList.length:null,riskyUsersAvailable:securityRisk.ok,riskyUsersReason:securityRisk.ok?null:String(securityRisk.error?.message||''),riskyUserList:securityRisk.ok?riskyUserList.map(u=>({id:u.id,name:u.userDisplayName||u.userPrincipalName,riskLevel:u.riskLevel,riskState:u.riskState,riskLastUpdated:u.riskLastUpdatedDateTime})):[],privilegedUsers,privilegedUsersAvailable:roleAssignments.ok,conditionalAccessPolicies:conditionalAccess.ok?(conditionalAccess.data.value||[]).length:null,conditionalAccessAvailable:conditionalAccess.ok,conditionalAccessPolicyList:conditionalAccess.ok?(conditionalAccess.data.value||[]).map(p=>({id:p.id,name:p.displayName,state:p.state})):[],credentialExpiry:{available:appCredentials.ok,items:credentialExpiryItems.slice(0,50),expiringSoon:appCredentials.ok?credentialExpiryItems.filter(i=>i.daysRemaining<=30).length:null,expiringWithin90:appCredentials.ok?credentialExpiryItems.filter(i=>i.daysRemaining>30&&i.daysRemaining<=90).length:null},applicationList:ownApps.map(a=>({id:a.id,appId:a.appId,name:a.displayName||a.appId})),deviceList:deviceRecords.map(d=>({id:d.id,name:d.displayName,os:d.operatingSystem,osVersion:d.operatingSystemVersion,trustType:d.trustType,compliant:d.isCompliant,enabled:d.accountEnabled,lastSignIn:d.approximateLastSignInDateTime})),healthScore,healthInputs,healthContributors:scoreContributors,healthExcludedSignals:excludedSignals,permissions,securityPermissionReady:securityRisk.ok&&roleAssignments.ok&&conditionalAccess.ok,collectedAt,coreQueryFailures:core.map((r,i)=>r.status==='rejected'?{index:i,error:String(r.reason?.message||r.reason)}:null).filter(Boolean)};
}
function fmtPct(ratio){return ratio==null?'—':`${(ratio*100).toFixed(1)}%`;}
const SKU_NAMES={SPE_E3:'Microsoft 365 E3',SPE_E5:'Microsoft 365 E5',SPE_F1:'Microsoft 365 F3',ENTERPRISEPACK:'Office 365 E3',ENTERPRISEPREMIUM:'Office 365 E5',ENTERPRISEWITHSCAL:'Office 365 E4',STANDARDPACK:'Office 365 E1',EMS:'Enterprise Mobility + Security E3',EMSPREMIUM:'Enterprise Mobility + Security E5',AAD_PREMIUM:'Microsoft Entra ID P1',AAD_PREMIUM_P2:'Microsoft Entra ID P2',POWER_BI_PRO:'Power BI Pro',POWER_BI_STANDARD:'Power BI Free',FLOW_FREE:'Power Automate Free',O365_BUSINESS_PREMIUM:'Microsoft 365 Business Standard',SPB:'Microsoft 365 Business Premium',SPE_E5_NOPSTNCONF:'Microsoft 365 E5 (no audio conferencing)'};
function friendlySkuName(code){return SKU_NAMES[code]||code||'Unknown SKU';}
export async function getLicenseSnapshot(){
 const collectedAt=new Date().toISOString();
 const skusResult=await graphGetOptional('/subscribedSkus?$select=skuId,skuPartNumber,consumedUnits,prepaidUnits,capabilityStatus',LICENSE_SCOPES);
 const usersResult=await graphGetOptional('/users?$top=999&$select=id,displayName,userPrincipalName,accountEnabled,assignedLicenses,signInActivity',CORE_SCOPES);
 const users=usersResult.ok?(usersResult.data.value||[]):[];
 const staleCutoff=Date.now()-90*86400000;
 const licensedUsers=users.filter(u=>(u.assignedLicenses||[]).length>0);
 const staleLicensedUsers=licensedUsers.filter(u=>u.accountEnabled!==false&&(!u.signInActivity?.lastSignInDateTime||new Date(u.signInActivity.lastSignInDateTime).getTime()<staleCutoff));
 const skus=(skusResult.ok?(skusResult.data.value||[]):[]).map(s=>{const purchased=s.prepaidUnits?.enabled||0;const consumed=s.consumedUnits||0;return {skuId:s.skuId,skuPartNumber:s.skuPartNumber,name:friendlySkuName(s.skuPartNumber),purchased,consumed,available:Math.max(0,purchased-consumed),suspended:s.prepaidUnits?.suspended||0,warning:s.prepaidUnits?.warning||0,capabilityStatus:s.capabilityStatus};}).sort((a,b)=>b.purchased-a.purchased);
 return {
  licensesAvailable:skusResult.ok,skus,
  totalPurchased:skusResult.ok?skus.reduce((a,s)=>a+s.purchased,0):null,
  totalConsumed:skusResult.ok?skus.reduce((a,s)=>a+s.consumed,0):null,
  totalAvailable:skusResult.ok?skus.reduce((a,s)=>a+s.available,0):null,
  licensedUsersAvailable:usersResult.ok,
  licensedUserCount:usersResult.ok?licensedUsers.length:null,
  staleLicensedUserCount:usersResult.ok?staleLicensedUsers.length:null,
  staleLicensedUsers:usersResult.ok?staleLicensedUsers.slice(0,25).map(u=>({name:u.displayName||u.userPrincipalName,upn:u.userPrincipalName,lastSignIn:u.signInActivity?.lastSignInDateTime||null})):[],
  collectedAt
 };
}
export async function getSignInTrend(days=30){return dailySignIns(days);}
export async function signOut(){const instance=getMsal();if(!instance)return;await initPromise;sessionStorage.removeItem('iam_tenant_connected');sessionStorage.removeItem('iam_tenant_id');sessionStorage.removeItem('iam_connect_pending');await instance.logoutRedirect({postLogoutRedirectUri:window.location.origin});}
