import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import {connectSecurityScopes,connectLicenseScopes,getLicenseSnapshot,getSignInTrend,signOut} from './entraAuth.js';
import {DATA_SOURCES,getActiveSource,setActiveSource,sourceById,checkAdAgent,getAdSnapshot,checkCollector,getCombinedSnapshot,getTenantDelta,getAppEvents} from './dataSources.js';
import {syncLiveTenantData} from './liveTenantData.js';

const NAV_GROUPS=[
  {section:null,items:[['Overview','⌂']]},
  {section:'Directory',items:[['Users','♙'],['Groups','♧'],['Devices','▱'],['Applications','▦']]},
  {section:'Identity Risk',items:[['Risk Overview','◈'],['Non-Human Identities','⚶'],['Toxic Combinations','☠'],['Sign-ins','↪'],['Conditional Access','◌'],['Alerts','⚑']]},
  {section:'Governance',items:[['Risk Register','▤'],['Licenses','◫'],['Access Reviews','◐'],['Provisioning','⇄']]},
  {section:'Admin',items:[['Audit Logs','▥'],['Reports','▧'],['Workflows','⚙'],['Data Explorer','⌕'],['Data Sources','◈'],['Settings','⚒']]},
];
// Labels rendered in the sidebar but with no working detail view yet - shown as
// a "Coming soon" placeholder on click instead of being hidden outright, so the
// roadmap is visible rather than making it look like functionality disappeared.
const PLACEHOLDER_LABELS=new Set(['Access Reviews','Provisioning','Audit Logs','Alerts','Workflows','Reports','Data Explorer','Settings']);
// Which nav labels appear for each source today. Working views plus the
// placeholder labels above (placeholders only make sense once real Entra
// data is flowing, so they're scoped to the entra source).
const NAV_BY_SOURCE={
  entra:['Overview','Users','Groups','Devices','Applications','Risk Overview','Non-Human Identities','Toxic Combinations','Sign-ins','Conditional Access','Risk Register','Licenses','Data Sources',...PLACEHOLDER_LABELS],
  ad:['Overview','Data Sources'],
  combined:['Overview','Data Sources'],
  sailpoint:['Data Sources'],
  saviynt:['Data Sources'],
};
function ComingSoonPage({label}){
  return <div className="source-page"><section className="grid top-grid single"><Card title={label}><div className="empty-state large">{label} isn't built yet. It's on the roadmap - this entry stays visible so the plan is transparent rather than hiding the gap.</div></Card></section></div>;
}
// Floor is 30s, not lower: each refresh re-runs ~20 live Graph queries against the
// tenant, and polling much faster than this risks Microsoft Graph 429 throttling.
// See docs/ARCHITECTURE.md "Refresh cadence" for the collector-backed alternative
// that can safely go sub-10s without hitting Graph on every tick.
const REFRESH_SECONDS=Math.max(30,Number(import.meta.env.VITE_REFRESH_INTERVAL_SECONDS)||30);
const fmt=n=>n==null?'—':Number(n).toLocaleString();
const pct=(n,d)=>n==null||!d?'—':`${((n/d)*100).toFixed(1)}%`;
const EXCEPTIONS_KEY='iam_attention_exceptions';
function loadExceptions(){try{return JSON.parse(localStorage.getItem(EXCEPTIONS_KEY)||'{}');}catch{return{};}}
function saveExceptions(map){try{localStorage.setItem(EXCEPTIONS_KEY,JSON.stringify(map));}catch{/* ignore quota/private-mode errors */}}
function Icon({children}){return <span className="nav-icon">{children}</span>}
function Card({title,children,actionLabel,onAction,className=''}){return <div className={`card ${className}`}><div className="card-header"><h3>{title}</h3>{actionLabel&&<button className="header-action" onClick={onAction}>{actionLabel}</button>}</div>{children}</div>}
function Donut({segments,total,label}){const sum=segments.reduce((a,s)=>a+(s.value||0),0)||1;let cursor=0;const stops=segments.map(s=>{const start=cursor;cursor+=(s.value||0)/sum*100;return `${s.color} ${start}% ${cursor}%`;}).join(',');return <div className="donut" style={{background:`conic-gradient(${stops})`}}><div className="donut-hole"><strong>{fmt(total)}</strong><span>{label}</span></div></div>}
function BarChart({items}){const max=Math.max(...items.map(x=>x.value||0),1);return <div className="bar-chart">{items.map((x,i)=><div className="bar-col" key={`${x.name}-${i}`}><div className="bar-value">{fmt(x.value)}</div><div className={`bar b${i%5}`} style={{height:`${Math.max(9,(x.value/max)*125)}px`}}></div><span title={x.name}>{x.name}</span></div>)}</div>}
function Sparkline({points}){const usable=points.filter(p=>p.total!=null);if(!usable.length)return <div className="empty-state">No sign-in trend data available.</div>;const max=Math.max(...usable.map(p=>p.total),1);const coords=usable.map((p,i)=>`${(i/Math.max(1,usable.length-1))*392+8},${84-(p.total/max)*70}`).join(' ');return <svg className="spark" viewBox="0 0 408 92" preserveAspectRatio="none"><polyline points={coords} fill="none" stroke="currentColor" strokeWidth="2.5"/><line x1="0" y1="88" x2="408" y2="88" stroke="rgba(255,255,255,.07)"/><line x1="0" y1="44" x2="408" y2="44" stroke="rgba(255,255,255,.05)"/></svg>}
function Status({ok,label='Live'}){return <span className={`status-pill ${ok?'ok':'warn'}`}><i/> {ok?label:'Permission required'}</span>}

function useFilter(){const [q,setQ]=useState('');return [q,setQ];}
function FilterBar({q,onQ,placeholder,children,count,total}){return <div className="detail-toolbar"><div className="filter-bar"><input className="filter-input" placeholder={placeholder} value={q} onChange={e=>onQ(e.target.value)}/>{children}</div><span className="filter-count">{count===total?`${fmt(total)} total`:`${fmt(count)} of ${fmt(total)}`}</span></div>}

function UsersDetailPage({data}){
  const [mfaQ,setMfaQ]=useFilter();const [staleQ,setStaleQ]=useFilter();const [staleDays,setStaleDays]=useState(90);
  const mfaMissing=data.mfa?.missingUsers||[];
  const staleCutoff=Date.now()-staleDays*86400000;
  const staleComputed=(data.userActivityList||[]).filter(u=>u.enabled!==false&&(!u.lastSignIn||new Date(u.lastSignIn).getTime()<staleCutoff));
  const mfaFiltered=mfaMissing.filter(u=>!mfaQ||`${u.name} ${u.upn}`.toLowerCase().includes(mfaQ.toLowerCase()));
  const staleFiltered=staleComputed.filter(u=>!staleQ||`${u.name} ${u.upn}`.toLowerCase().includes(staleQ.toLowerCase()));
  return <div className="source-page">
    <section className="kpis">{[['Total Users',data.users,'♙'],['Without MFA',data.mfa?.missing,'⚠'],['Stale (90+ Days)',data.staleUsers,'◔'],['Without Manager',data.usersWithoutManager,'◌']].map(([t,v,g])=><div className="kpi" key={t}><div className="kpi-icon">{g}</div><div><div className="kpi-title">{t}</div><div className="kpi-value">{fmt(v)}</div><div className="kpi-change"><span>Live Graph query</span></div></div></div>)}</section>
    <section className="grid top-grid single"><Card title="Users Without MFA">{data.mfa?.missing==null?<div className="empty-state">Permission required (AuditLog.Read.All / authentication methods report).</div>:<><FilterBar q={mfaQ} onQ={setMfaQ} placeholder="Search name or UPN…" count={mfaFiltered.length} total={mfaMissing.length}/><div className="license-table"><table><thead><tr><th>Name</th><th>User Principal Name</th></tr></thead><tbody>{mfaFiltered.slice(0,200).map(u=><tr key={u.id}><td>{u.name}</td><td>{u.upn}</td></tr>)}</tbody></table></div></>}<div className="disclaimer">Source: /reports/authenticationMethods/userRegistrationDetails. A user here has no registered MFA method as of last collection - it does not confirm they've never used MFA historically.</div></Card></section>
    <section className="grid top-grid single"><Card title="Stale Enabled Users">{!data.userActivityAvailable?<div className="empty-state">Permission required (User.Read.All).</div>:<><FilterBar q={staleQ} onQ={setStaleQ} placeholder="Search name or UPN…" count={staleFiltered.length} total={data.userActivityList.length}><select className="filter-select" value={staleDays} onChange={e=>setStaleDays(Number(e.target.value))}><option value={30}>No sign-in 30+ days</option><option value={60}>No sign-in 60+ days</option><option value={90}>No sign-in 90+ days</option><option value={180}>No sign-in 180+ days</option></select></FilterBar><div className="license-table"><table><thead><tr><th>Name</th><th>User Principal Name</th><th>Last Sign-in</th></tr></thead><tbody>{staleFiltered.slice(0,200).map(u=><tr key={u.id}><td>{u.name}</td><td>{u.upn}</td><td>{u.lastSignIn?new Date(u.lastSignIn).toLocaleDateString():'Never observed'}</td></tr>)}</tbody></table></div></>}<div className="disclaimer">"Never observed" means Graph's signInActivity field has no recorded sign-in, which is only populated going forward from when your tenant's license began tracking it - it is not proof the account was never used. The Overview KPI always uses the fixed 90-day window; this table's threshold is adjustable for investigation.</div></Card></section>
  </div>;
}

const DELTA_LABELS={applications:'Applications',users:'Users',groups:'Groups',devices:'Devices',risky_users:'Risky Users',privileged_users:'Privileged Users',stale_users:'Stale Users',mfa_missing:'Users Without MFA',credential_expiring_soon:'Credentials Expiring ≤30d',toxic_combinations:'Toxic Combinations'};
function useCollectorHistory(tenantId,days){
  const [delta,setDelta]=useState(null);const [events,setEvents]=useState(null);
  useEffect(()=>{if(!tenantId)return;setDelta(null);setEvents(null);getTenantDelta(tenantId,days).then(setDelta);getAppEvents(tenantId,days).then(setEvents);},[tenantId,days]);
  return {delta,events};
}
function TrendCard({tenantId,trendDays,setTrendDays,delta}){
  const row=delta?.ok&&delta.data.available?delta.data.deltas[metricKey]:null;
  return <Card title="Growth Trend"><div className="detail-toolbar"><span className="filter-count">{!tenantId?'Tenant ID unavailable':!delta?'Loading…':!delta.ok?delta.reason:!delta.data.available?delta.data.reason:`Since ${new Date(delta.data.sinceDate).toLocaleDateString()}`}</span><div className="filter-bar">{[7,30,90].map(d=><button key={d} className={`source-tab ${trendDays===d?'active':''}`} onClick={()=>setTrendDays(d)}>{d}D</button>)}</div></div>{row&&<div className="license-table"><table><thead><tr><th>Metric</th><th>{trendDays}d ago</th><th>Now</th><th>Change</th></tr></thead><tbody>{Object.entries(delta.data.deltas).filter(([,v])=>v).map(([key,v])=><tr key={key}><td>{DELTA_LABELS[key]||key}</td><td>{fmt(v.from)}</td><td>{fmt(v.to)}</td><td className={v.change>0&&['risky_users','stale_users','mfa_missing','credential_expiring_soon','toxic_combinations'].includes(key)?'text-critical':''}>{v.change>0?'+':''}{fmt(v.change)} ({v.pct==null?'—':`${v.pct>=0?'+':''}${v.pct.toFixed(1)}%`})</td></tr>)}</tbody></table></div>}<div className="disclaimer">Requires the collector (collector/) running and tracking this tenant's ID - appends one row per poll to build real history, unlike the live single-tenant view which only ever shows "now".</div></Card>;
}
function AppEventsCard({events}){
  const list=events?.ok?events.data.events:[];
  return <Card title="Recently Registered Applications">{!events?<div className="empty-state">Loading…</div>:!events.ok?<div className="empty-state">{events.reason}</div>:!list.length?<div className="empty-state">No new application registrations observed by the collector in this window.</div>:<div className="license-table"><table><thead><tr><th>Application</th><th>Registered</th><th>Source</th></tr></thead><tbody>{list.map(e=><tr key={e.audit_id}><td>{e.app_name||e.app_id||'Unknown'}</td><td>{new Date(e.activity_datetime).toLocaleString()}</td><td>{e.actor_type==='application'?`Automation${e.actor_name?': '+e.actor_name:''}`:e.actor_type==='user'?`Person${e.actor_name?': '+e.actor_name:''}`:'Unknown'}</td></tr>)}</tbody></table></div>}<div className="disclaimer">Source = who/what performed the "Add application" audit event: a person (interactive sign-in) or an automation using its own credential (Terraform, CI/CD, a script). Graph doesn't expose finer detail than that.</div></Card>;
}

function ApplicationsDetailPage({data}){
  const [q,setQ]=useFilter();const [bucket,setBucket]=useState('all');const [credThreshold,setCredThreshold]=useState(30);const [trendDays,setTrendDays]=useState(30);
  const tenantId=data.organization?.id;
  const {delta,events}=useCollectorHistory(tenantId,trendDays);
  const details=data.appDetails||[];
  const filtered=details.filter(a=>(bucket==='all'||a.bucket===bucket)&&(!q||a.name.toLowerCase().includes(q.toLowerCase())));
  const credByApp=new Map((data.credentialExpiry?.items||[]).map(c=>[c.appId,c]));
  return <div className="source-page">
    <section className="kpis">{[['Total Applications',data.applications,'▦'],['Active (≤30d)',data.appActivity?.active30,'✓'],['Inactive 90+ Days',(data.appActivity?.inactive91to180||0)+(data.appActivity?.inactive180||0),'⚠'],['Credentials ≤30d',data.credentialExpiry?.expiringSoon,'⏱']].map(([t,v,g])=><div className="kpi" key={t}><div className="kpi-icon">{g}</div><div><div className="kpi-title">{t}</div><div className="kpi-value">{fmt(v)}</div><div className="kpi-change"><span>Live Graph query</span></div></div></div>)}</section>
    <section className="grid top-grid single"><TrendCard tenantId={tenantId} trendDays={trendDays} setTrendDays={setTrendDays} delta={delta}/></section>
    <section className="grid top-grid single"><AppEventsCard events={events}/></section>
    <section className="grid top-grid single"><Card title="Application Inventory">{!data.appActivityAvailable?<div className="empty-state">{data.appActivityReason?`Activity data unavailable: ${data.appActivityReason}`:'Service-principal activity report unavailable - showing inventory only.'}</div>:null}<FilterBar q={q} onQ={setQ} placeholder="Search application name…" count={filtered.length} total={details.length}><select className="filter-select" value={bucket} onChange={e=>setBucket(e.target.value)}><option value="all">All statuses</option><option value="active">Active (≤30d)</option><option value="31-90">Inactive 31-90d</option><option value="91-180">Inactive 91-180d</option><option value="180+">Inactive &gt;180d</option></select><select className="filter-select" value={credThreshold} onChange={e=>setCredThreshold(Number(e.target.value))}><option value={15}>Flag credentials ≤15d</option><option value={30}>Flag credentials ≤30d</option><option value={60}>Flag credentials ≤60d</option><option value={90}>Flag credentials ≤90d</option></select></FilterBar><div className="license-table"><table><thead><tr><th>Application</th><th>Status</th><th>Days Since Activity</th><th>Credential Expiry</th></tr></thead><tbody>{filtered.slice(0,300).map(a=>{const cred=credByApp.get(a.appId);return <tr key={a.appId}><td>{a.name}</td><td>{a.bucket==='active'?'Active':`Inactive (${a.bucket}d)`}</td><td>{a.days==null?'Never observed':fmt(a.days)}</td><td className={cred&&cred.daysRemaining<=credThreshold?'text-critical':''}>{cred?`${cred.daysRemaining<0?'Expired':cred.daysRemaining+'d'} (${cred.type})`:'—'}</td></tr>})}</tbody></table></div><div className="disclaimer">Status is calculated from /reports/servicePrincipalSignInActivities (beta), matched to this tenant's own {fmt(data.applications)} app registrations only - Microsoft first-party service principals are excluded.</div></Card></section>
  </div>;
}

function ToxicCombinationsPage({data}){
  const [exceptions,setExceptions]=useState(loadExceptions());
  const acknowledge=(id,name)=>{const note=window.prompt(`Note for accepting risk on ${name} (why is this acceptable)?`);if(note==null)return;const key=`toxic-${id}`;const next={...exceptions,[key]:{note,at:new Date().toISOString(),title:`Toxic combination: ${name}`,category:'Toxic Combination'}};setExceptions(next);saveExceptions(next);};
  if(!data.toxicCombinationsAvailable)return <div className="source-page"><div className="empty-state large">Requires privileged-role data (RoleManagement.Read.Directory) plus at least one of MFA registration, ID Protection risk, or sign-in activity data.</div></div>;
  const all=data.toxicCombinations||[];
  const active=all.filter(c=>!exceptions[`toxic-${c.id}`]);
  const acked=all.filter(c=>exceptions[`toxic-${c.id}`]);
  return <div className="source-page">
    <section className="kpis"><div className="kpi"><div className="kpi-icon">☠</div><div><div className="kpi-title">Active Toxic Combinations</div><div className="kpi-value">{fmt(active.length)}</div><div className="kpi-change"><span>Privileged + a second risk signal</span></div></div></div></section>
    <section className="grid top-grid single"><Card title="Privileged Accounts With a Compounding Risk Signal">{!active.length?<div className="empty-state">No privileged account currently combines a second risk signal (missing MFA, ID Protection risk, or 90+ day staleness).</div>:<div className="license-table"><table><thead><tr><th>User</th><th>Compounding Signals</th><th></th></tr></thead><tbody>{active.map(c=><tr key={c.id}><td>{c.name}</td><td>{c.flags.join(', ')}</td><td><button className="attention-ack" title="Acknowledge with exception note" onClick={()=>acknowledge(c.id,c.name)}>✓</button></td></tr>)}</tbody></table></div>}<div className="disclaimer">Privileged = assigned a detected built-in Administrator/Global Reader/Security Reader/Privileged Role Administrator role. A user needs privileged access AND at least one other live signal to appear here - never a guess.</div></Card></section>
    {acked.length>0&&<section className="grid top-grid single"><Card title={`Acknowledged (${acked.length})`}><div className="license-table"><table><thead><tr><th>User</th><th>Note</th></tr></thead><tbody>{acked.map(c=><tr key={c.id}><td>{c.name}</td><td>{exceptions[`toxic-${c.id}`].note}</td></tr>)}</tbody></table></div></Card></section>}
  </div>;
}

function RiskRegisterPage(){
  const [exceptions,setExceptions]=useState(loadExceptions());
  const unacknowledge=key=>{const next={...exceptions};delete next[key];setExceptions(next);saveExceptions(next);};
  const entries=Object.entries(exceptions).sort((a,b)=>new Date(b[1].at)-new Date(a[1].at));
  return <div className="source-page"><section className="grid top-grid single"><Card title={`Risk Register (${entries.length} exception${entries.length===1?'':'s'})`}>{!entries.length?<div className="empty-state large">No exceptions acknowledged yet. Acknowledge a Need Attention or Toxic Combination finding to add it here with an audit note.</div>:<div className="license-table"><table><thead><tr><th>Finding</th><th>Category</th><th>Note</th><th>Acknowledged</th><th></th></tr></thead><tbody>{entries.map(([key,ex])=><tr key={key}><td>{ex.title||key}</td><td>{ex.category||'—'}</td><td>{ex.note}</td><td>{new Date(ex.at).toLocaleString()}</td><td><button className="ack-chip" onClick={()=>unacknowledge(key)}>Undo</button></td></tr>)}</tbody></table></div>}<div className="disclaimer">Stored in this browser's local storage only - not shared across users or synced yet. Treat this as a personal working register, not a compliance record of record, until backend storage is added to the collector.</div></Card></section></div>;
}

function DevicesDetailPage({data}){
  const [q,setQ]=useFilter();
  const devices=data.deviceList||[];
  const filtered=devices.filter(d=>!q||`${d.name} ${d.os}`.toLowerCase().includes(q.toLowerCase()));
  return <div className="source-page">
    <section className="kpis">{[['Total Devices',data.devices,'▱'],['Compliant',devices.filter(d=>d.compliant).length,'✓'],['Non-Compliant',devices.filter(d=>d.compliant===false).length,'⚠']].map(([t,v,g])=><div className="kpi" key={t}><div className="kpi-icon">{g}</div><div><div className="kpi-title">{t}</div><div className="kpi-value">{fmt(v)}</div><div className="kpi-change"><span>Live Graph query</span></div></div></div>)}</section>
    <section className="grid top-grid single"><Card title="Device Inventory">{!devices.length?<div className="empty-state">No devices returned, or Device.Read.All not granted.</div>:<><FilterBar q={q} onQ={setQ} placeholder="Search name or OS…" count={filtered.length} total={devices.length}/><div className="license-table"><table><thead><tr><th>Device</th><th>OS</th><th>Trust Type</th><th>Compliant</th><th>Last Sign-in</th></tr></thead><tbody>{filtered.slice(0,300).map(d=><tr key={d.id}><td>{d.name}</td><td>{d.os} {d.osVersion}</td><td>{d.trustType||'—'}</td><td>{d.compliant==null?'—':d.compliant?'Yes':'No'}</td><td>{d.lastSignIn?new Date(d.lastSignIn).toLocaleDateString():'—'}</td></tr>)}</tbody></table></div></>}</Card></section>
  </div>;
}

function SignInsDetailPage({data,trend,trendDays,trendLoading,onRangeChange}){
  const [q,setQ]=useFilter();
  const signIns=data.recentSignIns||[];
  const filtered=signIns.filter(s=>!q||`${s.userDisplayName||''} ${s.userPrincipalName||''} ${s.appDisplayName||''}`.toLowerCase().includes(q.toLowerCase()));
  if(!data.signInsAvailable)return <div className="source-page"><div className="empty-state large">{data.signInsReason?`Sign-in data unavailable: ${data.signInsReason}`:'Sign-in log data is unavailable for this tenant.'}<br/><br/>This Graph API commonly requires an Entra ID P1/P2 license even when AuditLog.Read.All is granted - check your tenant's license in the Microsoft 365 admin center.</div></div>;
  return <div className="source-page">
    <section className="detail-toolbar"><span className="filter-count">Sign-in trend range</span><div className="filter-bar">{[7,30,90].map(d=><button key={d} className={`source-tab ${trendDays===d?'active':''}`} onClick={()=>onRangeChange(d)}>{d}D</button>)}</div></section>
    <section className="grid top-grid single"><Card title={`Sign-in Trend (${trendDays}D)`}>{trendLoading?<div className="empty-state">Loading…</div>:<><div className="chart-head"><span>{fmt(Math.max(...(trend||[]).map(x=>x.total||0),0))}</span><span>Peak daily count</span></div><Sparkline points={trend||[]}/></>}</Card></section>
    <section className="grid top-grid single"><Card title="Recent Sign-ins"><FilterBar q={q} onQ={setQ} placeholder="Search user or application…" count={filtered.length} total={signIns.length}/><div className="license-table"><table><thead><tr><th>Time</th><th>User</th><th>Application</th><th>Status</th><th>Risk</th></tr></thead><tbody>{filtered.slice(0,50).map((s,i)=>{const ok=s.status?.errorCode===0;return <tr key={s.id||i}><td>{new Date(s.createdDateTime).toLocaleString()}</td><td>{s.userDisplayName||s.userPrincipalName||'Service principal'}</td><td>{s.appDisplayName||'—'}</td><td className={ok?'':'text-critical'}>{ok?'Success':`Failed (${s.status?.errorCode})`}</td><td>{s.riskLevelAggregated||'none'}</td></tr>})}</tbody></table></div></Card></section>
  </div>;
}

function NonHumanIdentitiesPage({data}){
  const [q,setQ]=useFilter();
  const nhi=data.nonHumanIdentities||{};
  const credItems=(data.credentialExpiry?.items||[]);
  const inactive90Plus=(data.appActivity?.inactive91to180||0)+(data.appActivity?.inactive180||0);
  const ownerless=(nhi.ownerlessApps||[]).filter(a=>!q||a.name.toLowerCase().includes(q.toLowerCase()));
  if(!nhi.available)return <div className="source-page"><div className="empty-state large">Permission required (Application.Read.All) to inventory non-human identities.</div></div>;
  return <div className="source-page">
    <section className="kpis">{[['Service Principals','totalServicePrincipals','⚶'],['Managed Identities','managedIdentities','◆'],['App Registrations','appRegistrations','▦'],['Credential-Bearing','credentialBearing','⏱'],['Ownerless Apps','ownerlessCount','⚠']].map(([t,k,g])=><div className="kpi" key={t}><div className="kpi-icon">{g}</div><div><div className="kpi-title">{t}</div><div className="kpi-value">{fmt(nhi[k])}</div><div className="kpi-change"><span>Live Graph query</span></div></div></div>)}</section>
    <section className="grid top-grid single"><Card title="Ownerless Applications">{!ownerless.length&&!q?<div className="empty-state">No app registrations found without at least one assigned owner.</div>:<><FilterBar q={q} onQ={setQ} placeholder="Search application name…" count={ownerless.length} total={(nhi.ownerlessApps||[]).length}/><div className="license-table"><table><thead><tr><th>Application</th><th>App ID</th></tr></thead><tbody>{ownerless.slice(0,200).map(a=><tr key={a.appId}><td>{a.name}</td><td className="mono">{a.appId}</td></tr>)}</tbody></table></div></>}<div className="disclaimer">An app registration with no owner has no accountable human to review, rotate credentials, or confirm it's still needed - a common source of orphaned non-human identities. Source: /applications $expand=owners.</div></Card></section>
    <section className="grid top-grid single"><Card title="Credentials Expiring or Expired">{!credItems.length?<div className="empty-state">No client secrets or certificates found on tenant app registrations.</div>:<div className="cred-list">{credItems.slice(0,15).map((c,i)=><div key={`${c.appId}-${i}`} className="cred-row"><div><strong>{c.name}</strong><span>{c.type==='certificate'?'Certificate':'Client secret'} • expires {new Date(c.expiresAt).toLocaleDateString()}</span></div><b className={c.daysRemaining<=30?'critical':c.daysRemaining<=90?'warning':''}>{c.daysRemaining<0?'Expired':`${c.daysRemaining}d`}</b></div>)}</div>}<div className="disclaimer">A non-human identity's credential is its only proof of identity - an expired or long-forgotten secret is the highest-signal NHI risk. {fmt(inactive90Plus)} applications also show no observed activity for 90+ days; see Applications for the full inactivity breakdown.</div></Card></section>
  </div>;
}

function RiskDetailPage({data,onSecurity}){
  const risky=data.riskyUserList||[];
  if(!data.riskyUsersAvailable)return <div className="source-page"><div className="permission-banner"><div><strong>Risk data not available.</strong><span>{data.riskyUsersReason||'Requires IdentityRiskyUser.Read.All, which also requires an Entra ID P2 license in this tenant.'}</span></div><button className="primary" onClick={onSecurity}>Grant security permissions</button></div></div>;
  return <div className="source-page">
    <section className="kpis">{[['Total Users',data.users,'♙'],['Risky Users',data.riskyUsers,'♜'],['Privileged Users',data.privilegedUsersAvailable?data.privilegedUsers:null,'◈']].map(([t,v,g])=><div className="kpi" key={t}><div className="kpi-icon">{g}</div><div><div className="kpi-title">{t}</div><div className="kpi-value">{fmt(v)}</div><div className="kpi-change"><span>Live Graph query</span></div></div></div>)}</section>
    <section className="grid top-grid single"><Card title="Risky Users">{!risky.length?<div className="empty-state">0 users currently flagged by Entra ID Protection - confirmed from a live query, not an unmeasured default.</div>:<div className="license-table"><table><thead><tr><th>User</th><th>Risk Level</th><th>Risk State</th><th>Last Updated</th></tr></thead><tbody>{risky.map(u=><tr key={u.id}><td>{u.name}</td><td className={String(u.riskLevel).toLowerCase()==='high'?'text-critical':''}>{u.riskLevel}</td><td>{u.riskState}</td><td>{u.riskLastUpdated?new Date(u.riskLastUpdated).toLocaleString():'—'}</td></tr>)}</tbody></table></div>}<div className="disclaimer">Source: /identityProtection/riskyUsers. Requires Entra ID Protection (P2) to return meaningful data.</div></Card></section>
    <section className="grid top-grid single"><Card title="Privileged Role Assignments">{!data.privilegedUsersAvailable?<div className="empty-state">Permission required (RoleManagement.Read.Directory).</div>:<div className="empty-state">{fmt(data.privilegedUsers)} unique principals hold a detected built-in privileged role (Administrator/Global Reader/Security Reader/Privileged Role Administrator pattern match). Per-user role detail is not yet broken out individually.</div>}</Card></section>
  </div>;
}

function ConditionalAccessDetailPage({data,onSecurity}){
  const policies=data.conditionalAccessPolicyList||[];
  if(!data.conditionalAccessAvailable)return <div className="source-page"><div className="permission-banner"><div><strong>Conditional Access data not available.</strong><span>Requires Policy.Read.All.</span></div><button className="primary" onClick={onSecurity}>Grant security permissions</button></div></div>;
  return <div className="source-page"><section className="grid top-grid single"><Card title={`Conditional Access Policies (${fmt(policies.length)})`}>{!policies.length?<div className="empty-state">0 policies configured in this tenant.</div>:<div className="license-table"><table><thead><tr><th>Policy</th><th>State</th></tr></thead><tbody>{policies.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.state}</td></tr>)}</tbody></table></div>}</Card></section></div>;
}

function GroupsDetailPage({data}){
  return <div className="source-page"><section className="kpis"><div className="kpi"><div className="kpi-icon">♧</div><div><div className="kpi-title">Total Groups</div><div className="kpi-value">{fmt(data.groups)}</div><div className="kpi-change"><span>Live Graph query</span></div></div></div></section><section className="grid top-grid single"><Card title="Group Detail"><div className="empty-state large">Per-group membership and type breakdown isn't built yet - the count above is a live /groups query, not a placeholder. Full group detail is a planned next step.</div></Card></section></div>;
}

function EntraDashboard({data,onSecurity,onNavigate}){
  const [exceptions,setExceptions]=useState(loadExceptions());
  const acknowledge=key=>{const note=window.prompt('Note for this exception (why is it acceptable to exclude from Need Attention)?');if(note==null)return;const item=attention.find(a=>a.key===key);const next={...exceptions,[key]:{note,at:new Date().toISOString(),title:item?.title||key,category:'Need Attention'}};setExceptions(next);saveExceptions(next);};
  const unacknowledge=key=>{const next={...exceptions};delete next[key];setExceptions(next);saveExceptions(next);};
  const attention=[
    {key:'toxic',level:'critical',title:'Toxic Combinations (Privileged + Risk Signal)',detail:'Privileged accounts that also lack MFA, are flagged risky by ID Protection, or are stale 90+ days',value:data.toxicCombinationsAvailable?data.toxicCombinationsCount:null,nav:'Toxic Combinations'},
    {key:'mfa',level:'warning',title:'Users Without MFA',detail:'No registered MFA method in the authentication registration report',value:data.mfa?.missing,nav:'Users'},
    {key:'inactiveApps',level:'warning',title:'Inactive Applications > 90 Days',detail:'No observed service-principal sign-in activity for more than 90 days',value:data.appActivityAvailable?(data.appActivity?.inactive91to180||0)+(data.appActivity?.inactive180||0):null,nav:'Applications'},
    {key:'risk',level:'critical',title:'Risky Users',detail:'Users currently returned by Microsoft Entra ID Protection',value:data.riskyUsersAvailable?data.riskyUsers:null,nav:'Risk Overview'},
    {key:'stale',level:'warning',title:'Stale Enabled Users > 90 Days',detail:'Enabled accounts with no sign-in in the last 90 days',value:data.staleUsers,nav:'Users'},
    {key:'privileged',level:'critical',title:'Privileged Users',detail:'Unique principals assigned to detected built-in privileged roles',value:data.privilegedUsersAvailable?data.privilegedUsers:null,nav:'Risk Overview'},
    {key:'credentials',level:(data.credentialExpiry?.expiringSoon||0)>0?'critical':'warning',title:'App Credentials Expiring ≤30 Days',detail:'Client secrets or certificates on tenant app registrations expiring within 30 days',value:data.credentialExpiry?.available?data.credentialExpiry.expiringSoon:null,nav:'Applications'},
    {key:'ownerless',level:'warning',title:'Ownerless Applications',detail:'App registrations with no assigned owner to review or rotate their credentials',value:data.nonHumanIdentities?.available?data.nonHumanIdentities.ownerlessCount:null,nav:'Non-Human Identities'}
  ];
  const activeAttention=attention.filter(a=>!exceptions[a.key]);
  const acknowledgedAttention=attention.filter(a=>exceptions[a.key]);
  const attentionCount=activeAttention.reduce((n,x)=>n+(x.value||0),0);const b=data.appActivity||{};
  const appTotal=data.appPopulation??data.applications;
  const appSegments=[{value:b.active30,color:'#31b75a'},{value:b.inactive31to90,color:'#f1a21a'},{value:b.inactive91to180,color:'#e86c32'},{value:b.inactive180,color:'#e85555'}];
  const score=data.healthScore;
  const go=label=>onNavigate&&onNavigate(label);
  return <>
    {!data.securityPermissionReady&&<div className="permission-banner"><div><strong>Security intelligence permissions are not fully validated.</strong><span>Core Entra data is live. Grant the read-only security scopes to enable risk, privileged-role and Conditional Access analytics.</span></div><button className="primary" onClick={onSecurity}>Grant security permissions</button></div>}
    <section className="kpis">{[['Total Users',data.users,'users','♙','Users'],['Total Applications',data.applications,'apps','▦','Applications'],['Active Devices',data.devices,'devices','▱','Devices'],['Sign-ins (7D)',data.signIns7d,'signin','↪','Sign-ins'],['Risky Sign-ins (7D)',data.riskySignIns7d,'risk','♜','Sign-ins']].map(([title,value,type,glyph,target])=><button className={`kpi kpi-link ${type}`} key={title} onClick={()=>go(target)}><div className="kpi-icon">{glyph}</div><div><div className="kpi-title">{title}</div><div className="kpi-value">{fmt(value)}</div><div className="kpi-change"><span>View details →</span></div></div></button>)}</section>
    <section className="grid top-grid">
      <Card title="Application Usage Overview" className="usage"><div className="usage-body"><Donut segments={appSegments} total={appTotal} label="Observed Apps"/><div className="legend">{[['Active (≤30 Days)',b.active30,'green'],['Inactive (31–90 Days)',b.inactive31to90,'amber'],['Inactive (91–180 Days)',b.inactive91to180,'orange'],['Inactive (>180 Days)',b.inactive180,'red']].map(([name,v,c])=><div key={name}><i className={c}/>{name}<b>{fmt(v)} <small>{pct(v,appTotal)}</small></b></div>)}</div></div><button className="card-link" onClick={()=>go('Applications')}>{data.appActivityAvailable?`All ${fmt(appTotal)} tenant applications, matched by appId to service-principal activity. View details →`:'Beta activity report unavailable - showing application inventory only.'}</button></Card>
      <Card title="Applications Not Used > 90 Days">{!data.appActivityAvailable?<div className="empty-state">{data.appActivityReason?`Unavailable: ${data.appActivityReason}`:'Service-principal activity report unavailable.'}</div>:<BarChart items={(data.inactiveApps||[]).slice(0,5).map(x=>({name:x.name,value:x.days==null?0:x.days}))}/>}<button className="card-link" onClick={()=>go('Applications')}>Top inactive applications by days since last observed activity. View details →</button></Card>
      <Card title={`Need Attention (${fmt(attentionCount)})`} className="attention-card">{activeAttention.map(item=><div className="attention-item" key={item.title}><button className="attention-main" onClick={()=>go(item.nav)}><div className={`attention-icon ${item.level}`}>{item.level==='critical'?'♜':'▣'}</div><div className="attention-copy"><strong>{item.title}</strong><span>{item.detail}</span></div><b className={item.level}>{fmt(item.value)}</b></button>{item.value>0&&<button className="attention-ack" title="Acknowledge with exception note" onClick={()=>acknowledge(item.key)}>✓</button>}</div>)}{acknowledgedAttention.length>0&&<div className="attention-ack-footer">{acknowledgedAttention.length} exception(s) acknowledged: {acknowledgedAttention.map(a=><button key={a.key} className="ack-chip" title={`${exceptions[a.key].note} (${new Date(exceptions[a.key].at).toLocaleDateString()})`} onClick={()=>unacknowledge(a.key)}>{a.title} ✕</button>)}</div>}</Card>
    </section>
    <section className="grid lower-grid">
      <Card title="Identity Risk Overview">{!data.riskyUsersAvailable?<div className="empty-state">{data.riskyUsersReason?`Permission required: ${data.riskyUsersReason}`:'Risk data requires the IdentityRiskyUser.Read.All permission, which also requires an Entra ID P2 license in this tenant.'}</div>:<div className="risk-body"><Donut segments={[{value:Math.max(0,data.users-data.riskyUsers),color:'#31b75a'},{value:data.riskyUsers,color:'#e85555'}]} total={data.users} label="Users"/><div className="risk-legend"><div><i className="green"/>Not flagged<b>{fmt(Math.max(0,data.users-data.riskyUsers))} <small>{pct(Math.max(0,data.users-data.riskyUsers),data.users)}</small></b></div><div><i className="red"/>Risky users<b>{fmt(data.riskyUsers)} <small>{pct(data.riskyUsers,data.users)}</small></b></div></div></div>}<button className="card-link" onClick={()=>go('Risk Overview')}>{data.riskyUsersAvailable?'Green = confirmed 0 risk findings from Entra ID Protection, not "unmeasured". View details →':'Grant security permissions above to enable this card.'}</button></Card>
      <Card title="Sign-in Overview">{!data.signInsAvailable?<div className="empty-state">{data.signInsReason?`Sign-in data unavailable: ${data.signInsReason}`:'Sign-in log data is unavailable for this tenant. This Graph API commonly requires an Entra ID P1/P2 license even with AuditLog.Read.All granted.'}</div>:<><div className="chart-head"><span>{fmt(Math.max(...(data.signInTrend||[]).map(x=>x.total||0),0))}</span><span>Peak daily count</span></div><Sparkline points={data.signInTrend||[]}/><div className="chart-labels">{(data.signInTrend||[]).map(x=><span key={x.date}>{new Date(`${x.date}T00:00:00`).toLocaleDateString([], {month:'short',day:'numeric'})}</span>)}</div><div className="series"><span><i className="green"/>Daily sign-in count</span><span><i className="blue"/>Graph query</span></div></>}</Card>
      <Card title="Identity Health Score"><div className="score"><div className="score-number">{score==null?'—':score}<small>/100</small></div><b className={score==null?'unknown':score>=80?'good':score>=60?'warn':'bad'}>{score==null?'Insufficient data':score>=80?'Good':score>=60?'Needs attention':'At risk'}</b>{(data.healthContributors||[]).length>0&&<div className="score-breakdown">{data.healthContributors.map(c=><div key={c.key}><span>{c.label}</span><b>{Math.round(c.score)}</b></div>)}</div>}{(data.healthExcludedSignals||[]).length>0&&<small className="score-excluded">Excluded (unavailable): {data.healthExcludedSignals.join(', ')}</small>}</div></Card>
      <Card title={<><span>AI Recommendations</span><em className="beta">RULE-BASED</em></>} className="ai-card">{[['MFA Adoption',data.mfa?.missing==null?'Permission required':`${fmt(data.mfa.missing)} users are not registered for MFA.`,data.mfa?.missing==null?'Grant permission':'Review MFA gaps','blue','Users'],['Application Cleanup',!data.appActivityAvailable?'Beta activity report unavailable.':`${fmt((b.inactive91to180||0)+(b.inactive180||0))} applications show no observed sign-in activity for 90+ days.`,'Review applications','green','Applications'],['Stale Accounts',`${fmt(data.staleUsers)} enabled users have no sign-in in the last 90 days.`,'Review stale users','amber','Users'],['Privileged Access',data.privilegedUsersAvailable?`${fmt(data.privilegedUsers)} unique principals are assigned to detected privileged roles.`:'Permission required.','Review roles','purple','Risk Overview']].map(([t,d,btn,c,target])=><div className="ai-item" key={t}><div className={`ai-icon ${c}`}>✦</div><div className="ai-copy"><strong>{t}</strong><span>{d}</span></div><button onClick={()=>go(target)}>{btn}</button></div>)}</Card>
    </section>
    <section className="bottom-grid three"><Card title="Application Credential Expiry">{!data.credentialExpiry?.available?<div className="empty-state">Permission required to read application credentials.</div>:!data.credentialExpiry.items.length?<div className="empty-state">No client secrets or certificates found on tenant app registrations.</div>:<div className="cred-list">{data.credentialExpiry.items.slice(0,8).map((c,i)=><div key={`${c.appId}-${i}`} className="cred-row"><div><strong>{c.name}</strong><span>{c.type==='certificate'?'Certificate':'Client secret'} • expires {new Date(c.expiresAt).toLocaleDateString()}</span></div><b className={c.daysRemaining<=30?'critical':c.daysRemaining<=90?'warning':''}>{c.daysRemaining<0?'Expired':`${c.daysRemaining}d`}</b></div>)}</div>}<button className="card-link" onClick={()=>go('Applications')}>Read from Application.Read.All; a &lt;30 day badge means rotate now. View details →</button></Card><Card title="Recent Activity" className="activity-card">{!data.signInsAvailable?<div className="empty-state">{data.signInsReason?`Unavailable: ${data.signInsReason}`:'Sign-in log data is unavailable for this tenant.'}</div>:<table><thead><tr><th>Time</th><th>Activity</th><th>Actor</th><th>Target</th><th>Status</th><th>Risk</th></tr></thead><tbody>{(data.recentSignIns||[]).slice(0,8).map((s,i)=>{const ok=s.status?.errorCode===0;return <tr key={s.id||i}><td>{new Date(s.createdDateTime).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</td><td>{s.isInteractive?'Interactive sign-in':'Sign-in'}</td><td>{s.userDisplayName||s.userPrincipalName||'Service principal'}</td><td>{s.appDisplayName||s.resourceDisplayName||'Microsoft Entra'}</td><td className={ok?'success':'failed'}>{ok?'Success':'Failed'}</td><td className={String(s.riskLevelAggregated||'none').toLowerCase()}>{s.riskLevelAggregated||'none'}</td></tr>})}</tbody></table>}{data.signInsAvailable&&<button className="card-link" onClick={()=>go('Sign-ins')}>View full sign-in log →</button>}</Card><Card title="Tenant Evidence"><div className="evidence-list"><div><span>Tenant</span><strong>{data.organization.displayName||'Unknown organization'}</strong></div><div><span>Tenant ID</span><strong className="mono">{data.organization.id||'—'}</strong></div><div><span>Verified domains</span><strong>{data.organization.verifiedDomains?.map(x=>x.name).filter(Boolean).join(', ')||'—'}</strong></div><div><span>Last collection</span><strong>{new Date(data.collectedAt).toLocaleString()}</strong></div><div><span>Conditional Access policies</span><strong>{fmt(data.conditionalAccessPolicies)}</strong></div></div></Card></section>
  </>;
}

function ADDashboard({data}){if(!data)return <div className="empty-state large">Active Directory is selected but the agent has not returned a snapshot.</div>;return <><section className="kpis">{[['AD Users',data.userCount,'♙'],['Enabled Users',data.enabledUserCount,'✓'],['Groups',data.groupCount,'♧'],['Computers',data.computerCount,'▱'],['Domain Controllers',data.domainControllerCount,'◆']].map(([t,v,g])=><div className="kpi" key={t}><div className="kpi-icon">{g}</div><div><div className="kpi-title">{t}</div><div className="kpi-value">{fmt(v)}</div><div className="kpi-change"><span>Live AD Agent query</span></div></div></div>)}</section><section className="grid top-grid"><Card title="AD Identity Hygiene"><div className="ad-metrics"><div><b>{fmt(data.disabledUserCount)}</b><span>Disabled users</span></div><div><b>{fmt(data.staleUserCount)}</b><span>Stale enabled users</span></div><div><b>{fmt(data.usersWithoutManager)}</b><span>Users without manager</span></div><div><b>{fmt(data.privilegedUsers)}</b><span>Privileged users</span></div></div></Card><Card title="Computer Hygiene"><div className="ad-metrics"><div><b>{fmt(data.staleComputerCount)}</b><span>Stale computers</span></div><div><b>{fmt(data.computerCount-data.staleComputerCount)}</b><span>Active recent computers</span></div></div></Card><Card title="Domain Controllers"><div className="dc-list">{(data.domainControllers||[]).map(dc=><div key={dc.HostName}><strong>{dc.HostName}</strong><span>{dc.Site||'Default site'} • {dc.IPv4Address||'no IPv4'} {dc.IsReadOnly?'• RODC':''}</span></div>)}</div></Card></section><section className="bottom-grid"><Card title="Active Directory Source"><div className="evidence-list"><div><span>Domain</span><strong>{data.domain}</strong></div><div><span>Forest</span><strong>{data.forest}</strong></div><div><span>Stale threshold</span><strong>{fmt(data.staleDays)} days</strong></div><div><span>Collected</span><strong>{new Date(data.collectedAt).toLocaleString()}</strong></div></div></Card><Card title="Security Boundary"><div className="empty-state">AD data is collected read-only by the local IAM AD Agent. Entra sign-in and ID Protection metrics remain separate until you switch the source back to Microsoft Entra ID.</div></Card></section></>}

function CombinedDashboard({data,collectorStatus}){
  if(!collectorStatus.connected)return <div className="empty-state large">The multi-tenant collector is not reachable. {collectorStatus.detail}. See <span className="mono">collector/README.md</span> to run it.</div>;
  if(!data)return <div className="empty-state large">Waiting for collector data…</div>;
  const certs=collectorStatus.data?.tenants||[];
  return <>
    <section className="kpis">{[['Tenants',data.tenantCount,'◇'],['Total Users',data.users,'♙'],['Total Applications',data.applications,'▦'],['Risky Users',data.riskyUsers,'♜'],['Privileged Users',data.privilegedUsers,'◈']].map(([t,v,g])=><div className="kpi" key={t}><div className="kpi-icon">{g}</div><div><div className="kpi-title">{t}</div><div className="kpi-value">{fmt(v)}</div><div className="kpi-change"><span>Collector snapshot</span></div></div></div>)}</section>
    <section className="grid top-grid single"><Card title="Per-Tenant Breakdown"><div className="license-table"><table><thead><tr><th>Tenant</th><th>Users</th><th>Applications</th><th>Risky Users</th><th>Privileged Users</th><th>Credentials ≤30d</th><th>Collected</th></tr></thead><tbody>{data.perTenant.map(t=><tr key={t.tenantId}><td>{t.displayName}</td><td>{fmt(t.users)}</td><td>{fmt(t.applications)}</td><td>{fmt(t.riskyUsers)}</td><td>{fmt(t.privilegedUsers)}</td><td>{fmt(t.credentialExpiringSoon)}</td><td>{new Date(t.collectedAt).toLocaleString()}</td></tr>)}</tbody></table></div></Card></section>
    <section className="grid top-grid single"><Card title="Collector Certificate Health"><div className="license-table"><table><thead><tr><th>Tenant</th><th>Certificate expires</th><th>Days remaining</th></tr></thead><tbody>{certs.map(c=><tr key={c.id}><td>{c.displayName}</td><td>{c.certExpiresAt?new Date(c.certExpiresAt).toLocaleDateString():'—'}</td><td className={c.certExpiresInDays!=null&&c.certExpiresInDays<=30?'text-critical':''}>{c.certExpiresInDays!=null?`${c.certExpiresInDays}d`:'—'}</td></tr>)}</tbody></table></div><button className="card-link">The collector's certificate authenticates app-only Graph access. Rotate before 0 remaining days.</button></Card></section>
    <section className="grid top-grid single"><Card title="Application Credentials Expiring ≤30 Days (all tenants)">{!data.credentialExpiry.items.length?<div className="empty-state">No client secrets or certificates expiring soon across configured tenants.</div>:<div className="cred-list">{data.credentialExpiry.items.map((c,i)=><div key={`${c.appId}-${i}`} className="cred-row"><div><strong>{c.name}</strong><span>{c.tenant} • {c.type==='certificate'?'Certificate':'Client secret'} • expires {new Date(c.expiresAt).toLocaleDateString()}</span></div><b className={c.daysRemaining<=30?'critical':'warning'}>{c.daysRemaining<0?'Expired':`${c.daysRemaining}d`}</b></div>)}</div>}</Card></section>
  </>;
}

function DataSourcesPage({sourceId,onSelect,adStatus,collectorStatus}){const iconFor=id=>({entra:'◆',ad:'◇',combined:'⬡',sailpoint:'▣',saviynt:'◎'}[id]||'›');const statusFor=id=>{if(id==='entra')return {connected:true,detail:'Delegated Graph access'};if(id==='ad')return {connected:adStatus.connected,detail:adStatus.connected?'Agent online':'Agent required'};if(id==='combined')return {connected:collectorStatus.connected,detail:collectorStatus.connected?collectorStatus.detail:'Collector required'};return {connected:false,detail:'Connector not configured'};};return <div className="source-page"><div className="source-intro"><div><div className="builder-kicker">DATA SOURCES</div><h2>Identity source control plane</h2><p className="muted">Choose which identity system powers the dashboard. No source is shown as connected unless a live health check succeeds.</p></div></div><div className="source-grid">{DATA_SOURCES.map(s=>{const st=statusFor(s.id);return <button className={`source-card ${sourceId===s.id?'selected':''}`} key={s.id} onClick={()=>onSelect(s.id)}><div className="source-icon">{iconFor(s.id)}</div><div><strong>{s.name}</strong><span>{s.type}</span><small>{st.connected?'Connected • Live':st.detail}</small></div></button>})}</div><div className="agent-box"><h3>Active Directory Agent</h3><p className="muted">Run <span className="mono">agent/IAM-AD-Agent.ps1</span> on a domain-joined Windows host, then set <span className="mono">VITE_AD_AGENT_URL</span>. The dashboard validates <span className="mono">/health</span> before AD data becomes active.</p><div className="agent-status"><Status ok={adStatus.connected} label={adStatus.connected?'Agent online':'Agent unavailable'}/><span>{adStatus.detail}</span></div></div><div className="agent-box"><h3>Multi-Tenant Collector</h3><p className="muted">Run <span className="mono">collector/</span> (certificate-authenticated, on your own infrastructure), then set <span className="mono">VITE_COLLECTOR_URL</span>. Powers the "All Identity Sources" combined view across every configured tenant.</p><div className="agent-status"><Status ok={collectorStatus.connected} label={collectorStatus.connected?'Collector online':'Collector unavailable'}/><span>{collectorStatus.detail}</span></div></div></div>}

function LicensesPage({data,loading,onGrant}){
  if(!data?.licensesAvailable){
    return <div className="source-page"><div className="permission-banner"><div><strong>License permissions are not granted.</strong><span>Grant read-only Organization.Read.All to see purchased, consumed and available seats per Microsoft 365 / Entra license.</span></div><button className="primary" onClick={onGrant}>{loading?'Requesting…':'Grant license permissions'}</button></div>{data&&<div className="empty-state large">{loading?'Loading license data…':'License SKU data unavailable. Grant permission above.'}</div>}</div>;
  }
  return <div className="source-page">
    <section className="kpis">{[['Purchased Seats',data.totalPurchased,'♙'],['Assigned Seats',data.totalConsumed,'✓'],['Available Seats',data.totalAvailable,'◇'],['Stale Licensed Accounts',data.staleLicensedUserCount,'⚠']].map(([t,v,g])=><div className="kpi" key={t}><div className="kpi-icon">{g}</div><div><div className="kpi-title">{t}</div><div className="kpi-value">{fmt(v)}</div><div className="kpi-change"><span>Live Graph query</span></div></div></div>)}</section>
    <section className="grid top-grid single"><Card title={`License Inventory (${fmt(data.skus.length)} SKUs)`}><div className="license-table"><table><thead><tr><th>License</th><th>SKU code</th><th>Purchased</th><th>Assigned</th><th>Available</th><th>Utilization</th></tr></thead><tbody>{data.skus.map(s=><tr key={s.skuId}><td>{s.name}</td><td className="mono">{s.skuPartNumber}</td><td>{fmt(s.purchased)}</td><td>{fmt(s.consumed)}</td><td>{fmt(s.available)}</td><td>{pct(s.consumed,s.purchased)}</td></tr>)}</tbody></table></div></Card></section>
    <section className="grid top-grid single"><Card title="Recommendations">{(()=>{const recs=[...data.skus.filter(s=>s.purchased>0&&s.available>0&&(s.consumed/s.purchased)<0.8).map(s=>({t:`${fmt(s.available)} unused ${s.name} seats`,d:`Only ${pct(s.consumed,s.purchased)} of purchased seats are assigned. Consider reallocating or reducing the purchase.`})),...(data.staleLicensedUserCount?[{t:`${fmt(data.staleLicensedUserCount)} licensed accounts inactive 90+ days`,d:'These accounts hold at least one license but have no recent sign-in. Review for license reclamation.'}]:[])];return recs.length?recs.map((r,i)=><div className="ai-item" key={i}><div className="ai-icon amber">✦</div><div className="ai-copy"><strong>{r.t}</strong><span>{r.d}</span></div></div>):<div className="empty-state">No license optimization findings from the current data.</div>;})()}</Card></section>
    {data.staleLicensedUserCount>0&&<section className="grid top-grid single"><Card title="Stale Licensed Accounts"><div className="license-table"><table><thead><tr><th>User</th><th>UPN</th><th>Last sign-in</th></tr></thead><tbody>{data.staleLicensedUsers.map(u=><tr key={u.upn}><td>{u.name}</td><td>{u.upn}</td><td>{u.lastSignIn?new Date(u.lastSignIn).toLocaleDateString():'Never observed'}</td></tr>)}</tbody></table></div></Card></section>}
  </div>;
}

function App(){
  const [active,setActive]=useState('Overview');const [sourceId,setSourceId]=useState(getActiveSource());const [data,setData]=useState(window.__IAM_SNAPSHOT__||null);const [sourceData,setSourceData]=useState(null);const [loading,setLoading]=useState(!window.__IAM_SNAPSHOT__);const [toast,setToast]=useState('');const [adStatus,setAdStatus]=useState({configured:false,connected:false,detail:'Checking…'});const [licenseData,setLicenseData]=useState(null);const [licenseLoading,setLicenseLoading]=useState(false);const [collectorStatus,setCollectorStatus]=useState({configured:false,connected:false,detail:'Checking…'});const [combinedData,setCombinedData]=useState(null);const [signInTrend,setSignInTrend]=useState(null);const [signInTrendDays,setSignInTrendDays]=useState(7);const [signInTrendLoading,setSignInTrendLoading]=useState(false);
  useEffect(()=>{const h=e=>{setData(e.detail);setLoading(false)};document.addEventListener('iam-live-data',h);return()=>document.removeEventListener('iam-live-data',h)},[]);
  useEffect(()=>{checkAdAgent().then(setAdStatus)},[]);
  useEffect(()=>{checkCollector().then(setCollectorStatus)},[]);
  useEffect(()=>{if(sourceId==='ad'&&adStatus.connected){setLoading(true);getAdSnapshot().then(x=>{setSourceData(x);setLoading(false)}).catch(e=>{setSourceData(null);setLoading(false);setToast(e.message)})}else if(sourceId!=='ad')setSourceData(null)},[sourceId,adStatus.connected]);
  useEffect(()=>{if(sourceId==='combined'&&collectorStatus.connected){setLoading(true);getCombinedSnapshot().then(x=>{setCombinedData(x);setLoading(false)}).catch(e=>{setCombinedData(null);setLoading(false);setToast(e.message)})}else if(sourceId!=='combined')setCombinedData(null)},[sourceId,collectorStatus.connected]);
  useEffect(()=>{if(active==='Licenses'&&!licenseData&&!licenseLoading){setLicenseLoading(true);getLicenseSnapshot().then(d=>{setLicenseData(d);setLicenseLoading(false)}).catch(e=>{setLicenseLoading(false);setToast(e.message||'License data unavailable')})}},[active]);
  const loadSignInTrend=days=>{setSignInTrendDays(days);setSignInTrendLoading(true);getSignInTrend(days).then(setSignInTrend).catch(()=>setSignInTrend(null)).finally(()=>setSignInTrendLoading(false));};
  useEffect(()=>{if(active==='Sign-ins'&&sourceId==='entra'&&data?.signInsAvailable&&!signInTrend&&!signInTrendLoading)loadSignInTrend(7);},[active,sourceId,data]);
  const refreshingRef=useRef(false);
  useEffect(()=>{
    if(sourceId!=='entra')return;
    const id=setInterval(async()=>{
      if(refreshingRef.current||document.visibilityState!=='visible')return;
      refreshingRef.current=true;
      try{const snap=await syncLiveTenantData();setData(snap);}catch(e){console.error('IAM auto-refresh failed:',e);}
      finally{refreshingRef.current=false;}
    },REFRESH_SECONDS*1000);
    return()=>clearInterval(id);
  },[sourceId]);
  const refresh=async()=>{setLoading(true);try{if(sourceId==='entra'){const snap=await syncLiveTenantData();setData(snap);setToast('Entra data refreshed')}else if(sourceId==='ad'){const snap=await getAdSnapshot();setSourceData(snap);setToast('AD data refreshed')}else if(sourceId==='combined'){const snap=await getCombinedSnapshot();setCombinedData(snap);setToast('Combined data refreshed')}else setToast(`${sourceById(sourceId).name} is not configured`)}catch(e){setToast(e.message||'Refresh failed')}finally{setLoading(false);setTimeout(()=>setToast(''),3000)}};
  const chooseSource=id=>{setActiveSource(id);setSourceId(id);setActive('Overview');};
  const grantSecurity=async()=>{try{setToast('Requesting security permissions…');await connectSecurityScopes();setToast('Consent completed; refreshing security data…');await refresh()}catch(e){setToast(e.message||'Security consent failed')}setTimeout(()=>setToast(''),4000)};
  const grantLicense=async()=>{setLicenseLoading(true);try{setToast('Requesting license permissions…');await connectLicenseScopes();setToast('Consent completed; loading license data…');const d=await getLicenseSnapshot();setLicenseData(d);}catch(e){setToast(e.message||'License consent failed')}finally{setLicenseLoading(false);setTimeout(()=>setToast(''),4000)}};
  const title=active==='Licenses'?'Licenses':sourceId==='entra'?(active==='Overview'?'Executive Overview':active):sourceId==='ad'?(active==='Overview'?'Active Directory Overview':active):sourceById(sourceId).name;
  const visibleLabels=new Set(NAV_BY_SOURCE[sourceId]||['Overview','Data Sources']);
  const chooseNav=label=>{if(!visibleLabels.has(label))return;setActive(label);};
  let entraContent=sourceId==='entra'&&!data?<div className="empty-state large">Collecting live data from Microsoft Graph - this runs a full tenant query and can take a few seconds on first load or after a browser refresh.</div>:null;
  if(sourceId==='entra'&&data){
    if(active==='Users')entraContent=<UsersDetailPage data={data}/>;
    else if(active==='Groups')entraContent=<GroupsDetailPage data={data}/>;
    else if(active==='Applications')entraContent=<ApplicationsDetailPage data={data}/>;
    else if(active==='Devices')entraContent=<DevicesDetailPage data={data}/>;
    else if(active==='Risk Overview')entraContent=<RiskDetailPage data={data} onSecurity={grantSecurity}/>;
    else if(active==='Non-Human Identities')entraContent=<NonHumanIdentitiesPage data={data}/>;
    else if(active==='Sign-ins')entraContent=<SignInsDetailPage data={data} trend={signInTrend} trendDays={signInTrendDays} trendLoading={signInTrendLoading} onRangeChange={loadSignInTrend}/>;
    else if(active==='Conditional Access')entraContent=<ConditionalAccessDetailPage data={data} onSecurity={grantSecurity}/>;
    else if(active==='Toxic Combinations')entraContent=<ToxicCombinationsPage data={data}/>;
    else if(active==='Risk Register')entraContent=<RiskRegisterPage/>;
    else if(PLACEHOLDER_LABELS.has(active))entraContent=<ComingSoonPage label={active}/>;
    else entraContent=<EntraDashboard data={data} onSecurity={grantSecurity} onNavigate={chooseNav}/>;
  }
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><span>◆</span></div><div><div className="brand-name">IAM Intelligence</div><div className="brand-tag">Identity. Secure. Simplified.</div></div></div><nav>{NAV_GROUPS.map(g=>{const items=g.items.filter(([label])=>visibleLabels.has(label));if(!items.length)return null;return <React.Fragment key={g.section||'root'}>{g.section&&<div className="section-label">{g.section}</div>}{items.map(([label,glyph])=><button key={label} className={`nav-item ${active===label?'active':''}`} onClick={()=>chooseNav(label)}><Icon>{glyph}</Icon><span>{label}</span></button>)}</React.Fragment>})}</nav><div className="sidebar-footer">Source<br/><strong>{sourceById(sourceId).name}</strong></div></aside><main className="main"><header className="topbar"><div className="page-title"><span>{title}</span><span className="chevron">⌄</span></div><div className="top-actions"><div className="source-tabs">{DATA_SOURCES.map(s=><button key={s.id} className={`source-tab ${sourceId===s.id?'active':''}`} onClick={()=>chooseSource(s.id)} title={s.type}>{s.name}</button>)}</div><Status ok={sourceId==='entra'||(sourceId==='ad'&&adStatus.connected)} label="Live"/><button className="icon-btn" onClick={refresh} title="Refresh">↻</button><button className="icon-btn labeled" onClick={signOut}><span>⇥</span>Sign out</button><button className="filter-btn" onClick={()=>setActive('Data Sources')}>Data Sources</button></div></header><div className="content"><div className="live-row"><span className="live-dot"></span> Source: <strong>{sourceById(sourceId).name}</strong><span className="separator">•</span>{sourceId==='entra'?`Tenant: ${data?.organization?.displayName||'Loading…'}`:sourceId==='ad'?`Domain: ${sourceData?.domain||'Loading…'}`:sourceId==='combined'?`${combinedData?.tenantCount??'…'} tenant(s) via collector`:'Connector not configured'}<span className="separator">•</span>{loading?'Collecting live data…':`Last refresh ${data?.collectedAt?new Date(data.collectedAt).toLocaleTimeString():sourceData?.collectedAt?new Date(sourceData.collectedAt).toLocaleTimeString():combinedData?.collectedAt?new Date(combinedData.collectedAt).toLocaleTimeString():'—'}`}{sourceId==='entra'&&<><span className="separator">•</span>Auto-refresh every {REFRESH_SECONDS}s</>}</div>{active==='Data Sources'?<DataSourcesPage sourceId={sourceId} onSelect={chooseSource} adStatus={adStatus} collectorStatus={collectorStatus}/>:active==='Licenses'?<LicensesPage data={licenseData} loading={licenseLoading} onGrant={grantLicense}/>:sourceId==='entra'?entraContent:sourceId==='ad'?<ADDashboard data={sourceData}/>:sourceId==='combined'?<CombinedDashboard data={combinedData} collectorStatus={collectorStatus}/>:<div className="empty-state large">{sourceById(sourceId).name} connector is not configured. Open Data Sources to configure it.</div>}</div></main>{toast&&<div className="toast">✓ {toast}</div>}</div>;
}

createRoot(document.getElementById('root')).render(<App/>);
