import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import {connectSecurityScopes,connectLicenseScopes,getLicenseSnapshot,signOut} from './entraAuth.js';
import {DATA_SOURCES,getActiveSource,setActiveSource,sourceById,checkAdAgent,getAdSnapshot,checkCollector,getCombinedSnapshot} from './dataSources.js';
import {syncLiveTenantData} from './liveTenantData.js';

const nav=[['Overview','⌂'],['Users','♙'],['Groups','♧'],['Applications','▦'],['Devices','▱'],['Identities','◉'],['__Protection',''],['Risk Overview','◈'],['Sign-ins','↪'],['Access Reviews','▣'],['Conditional Access','◌'],['__Operations',''],['Provisioning','⇄'],['Audit Logs','≡'],['Alerts','♢'],['Workflows','◇'],['__Reports',''],['Reports','▤'],['Data Explorer','⌕'],['__Licensing',''],['Licenses','◫'],['__Admin',''],['Settings','⚙'],['Data Sources','◈']];
const REFRESH_SECONDS=Math.max(30,Number(import.meta.env.VITE_REFRESH_INTERVAL_SECONDS)||60);
const fmt=n=>n==null?'—':Number(n).toLocaleString();
const pct=(n,d)=>n==null||!d?'—':`${((n/d)*100).toFixed(1)}%`;
function Icon({children}){return <span className="nav-icon">{children}</span>}
function Card({title,children,actionLabel,onAction,className=''}){return <div className={`card ${className}`}><div className="card-header"><h3>{title}</h3>{actionLabel&&<button className="header-action" onClick={onAction}>{actionLabel}</button>}</div>{children}</div>}
function Donut({segments,total,label}){const sum=segments.reduce((a,s)=>a+(s.value||0),0)||1;let cursor=0;const stops=segments.map(s=>{const start=cursor;cursor+=(s.value||0)/sum*100;return `${s.color} ${start}% ${cursor}%`;}).join(',');return <div className="donut" style={{background:`conic-gradient(${stops})`}}><div className="donut-hole"><strong>{fmt(total)}</strong><span>{label}</span></div></div>}
function BarChart({items}){const max=Math.max(...items.map(x=>x.value||0),1);return <div className="bar-chart">{items.map((x,i)=><div className="bar-col" key={`${x.name}-${i}`}><div className="bar-value">{fmt(x.value)}</div><div className={`bar b${i%5}`} style={{height:`${Math.max(9,(x.value/max)*125)}px`}}></div><span title={x.name}>{x.name}</span></div>)}</div>}
function Sparkline({points}){const usable=points.filter(p=>p.total!=null);if(!usable.length)return <div className="empty-state">No sign-in trend data available.</div>;const max=Math.max(...usable.map(p=>p.total),1);const coords=usable.map((p,i)=>`${(i/Math.max(1,usable.length-1))*392+8},${84-(p.total/max)*70}`).join(' ');return <svg className="spark" viewBox="0 0 408 92" preserveAspectRatio="none"><polyline points={coords} fill="none" stroke="currentColor" strokeWidth="2.5"/><line x1="0" y1="88" x2="408" y2="88" stroke="rgba(255,255,255,.07)"/><line x1="0" y1="44" x2="408" y2="44" stroke="rgba(255,255,255,.05)"/></svg>}
function Status({ok,label='Live'}){return <span className={`status-pill ${ok?'ok':'warn'}`}><i/> {ok?label:'Permission required'}</span>}

function EntraDashboard({data,onSecurity}){
  const attention=[
    {level:'warning',title:'Users Without MFA',detail:'No registered MFA method in the authentication registration report',value:data.mfa?.missing},
    {level:'warning',title:'Inactive Applications > 90 Days',detail:'No observed service-principal sign-in activity for more than 90 days',value:(data.appActivity?.inactive91to180||0)+(data.appActivity?.inactive180||0)},
    {level:'critical',title:'Risky Users',detail:'Users currently returned by Microsoft Entra ID Protection',value:data.riskyUsers},
    {level:'warning',title:'Stale Enabled Users > 90 Days',detail:'Enabled accounts with no sign-in in the last 90 days',value:data.staleUsers},
    {level:'critical',title:'Privileged Users',detail:'Unique principals assigned to detected built-in privileged roles',value:data.privilegedUsers},
    {level:(data.credentialExpiry?.expiringSoon||0)>0?'critical':'warning',title:'App Credentials Expiring ≤30 Days',detail:'Client secrets or certificates on tenant app registrations expiring within 30 days',value:data.credentialExpiry?.available?data.credentialExpiry.expiringSoon:null}
  ];
  const attentionCount=attention.reduce((n,x)=>n+(x.value||0),0);const b=data.appActivity||{};
  const appSegments=[{value:b.active30,color:'#31b75a'},{value:b.inactive31to90,color:'#f1a21a'},{value:b.inactive91to180,color:'#e86c32'},{value:b.inactive180,color:'#e85555'}];
  const score=data.healthScore;
  return <>
    {!data.securityPermissionReady&&<div className="permission-banner"><div><strong>Security intelligence permissions are not fully validated.</strong><span>Core Entra data is live. Grant the read-only security scopes to enable risk, privileged-role and Conditional Access analytics.</span></div><button className="primary" onClick={onSecurity}>Grant security permissions</button></div>}
    <section className="kpis">{[['Total Users',data.users,'users','♙'],['Total Applications',data.applications,'apps','▦'],['Active Devices',data.devices,'devices','▱'],['Sign-ins (7D)',data.signIns7d,'signin','↪'],['Risky Sign-ins (7D)',data.riskySignIns7d,'risk','♜']].map(([title,value,type,glyph])=><div className={`kpi ${type}`} key={title}><div className="kpi-icon">{glyph}</div><div><div className="kpi-title">{title}</div><div className="kpi-value">{fmt(value)}</div><div className="kpi-change"><span>Live Graph query</span></div></div></div>)}</section>
    <section className="grid top-grid">
      <Card title="Application Usage Overview" className="usage"><div className="usage-body"><Donut segments={appSegments} total={data.applications} label="Observed Apps"/><div className="legend">{[['Active (≤30 Days)',b.active30,'green'],['Inactive (31–90 Days)',b.inactive31to90,'amber'],['Inactive (91–180 Days)',b.inactive91to180,'orange'],['Inactive (>180 Days)',b.inactive180,'red']].map(([name,v,c])=><div key={name}><i className={c}/>{name}<b>{fmt(v)} <small>{pct(v,data.applications)}</small></b></div>)}</div></div><button className="card-link">All values are calculated from live service-principal activity.</button></Card>
      <Card title="Applications Not Used > 90 Days"><BarChart items={(data.inactiveApps||[]).slice(0,5).map(x=>({name:x.name,value:x.days==null?0:x.days}))}/><button className="card-link">Top inactive applications by days since last observed activity.</button></Card>
      <Card title={`Need Attention (${fmt(attentionCount)})`} className="attention-card">{attention.map(item=><div className="attention-item" key={item.title}><div className={`attention-icon ${item.level}`}>{item.level==='critical'?'♜':'▣'}</div><div className="attention-copy"><strong>{item.title}</strong><span>{item.detail}</span></div><b className={item.level}>{fmt(item.value)}</b></div>)}</Card>
    </section>
    <section className="grid lower-grid">
      <Card title="Identity Risk Overview"><div className="risk-body"><Donut segments={[{value:Math.max(0,data.users-(data.riskyUsers||0)),color:'#31b75a'},{value:data.riskyUsers||0,color:'#e85555'}]} total={data.users} label="Users"/><div className="risk-legend"><div><i className="green"/>Not flagged<b>{fmt(Math.max(0,data.users-(data.riskyUsers||0)))} <small>{pct(Math.max(0,data.users-(data.riskyUsers||0)),data.users)}</small></b></div><div><i className="red"/>Risky users<b>{fmt(data.riskyUsers)} <small>{pct(data.riskyUsers,data.users)}</small></b></div></div></div><button className="card-link">Risk values come from ID Protection when permission is granted.</button></Card>
      <Card title="Sign-in Overview"><div className="chart-head"><span>{fmt(Math.max(...(data.signInTrend||[]).map(x=>x.total||0),0))}</span><span>Peak daily count</span></div><Sparkline points={data.signInTrend||[]}/><div className="chart-labels">{(data.signInTrend||[]).map(x=><span key={x.date}>{new Date(`${x.date}T00:00:00`).toLocaleDateString([], {month:'short',day:'numeric'})}</span>)}</div><div className="series"><span><i className="green"/>Daily sign-in count</span><span><i className="blue"/>Graph query</span></div></Card>
      <Card title="Identity Health Score"><div className="score"><div className="score-number">{score==null?'—':score}<small>/100</small></div><b>{score==null?'Insufficient data':score>=80?'Good':score>=60?'Needs attention':'At risk'}</b><small>Calculated from live MFA, risk, stale-user and app-hygiene signals.</small></div></Card>
      <Card title={<><span>AI Recommendations</span><em className="beta">LIVE</em></>} className="ai-card">{[['MFA Adoption',data.mfa?.missing==null?'Permission required':`${fmt(data.mfa.missing)} users are not registered for MFA.`,data.mfa?.missing==null?'Grant permission':'Review MFA gaps','blue'],['Application Cleanup',`${fmt((b.inactive91to180||0)+(b.inactive180||0))} applications show no observed sign-in activity for 90+ days.`,'Review applications','green'],['Stale Accounts',`${fmt(data.staleUsers)} enabled users have no sign-in in the last 90 days.`,'Review stale users','amber'],['Privileged Access',`${fmt(data.privilegedUsers)} unique principals are assigned to detected privileged roles.`,'Review roles','purple']].map(([t,d,btn,c])=><div className="ai-item" key={t}><div className={`ai-icon ${c}`}>✦</div><div className="ai-copy"><strong>{t}</strong><span>{d}</span></div><button>{btn}</button></div>)}</Card>
    </section>
    <section className="bottom-grid three"><Card title="Application Credential Expiry">{!data.credentialExpiry?.available?<div className="empty-state">Permission required to read application credentials.</div>:!data.credentialExpiry.items.length?<div className="empty-state">No client secrets or certificates found on tenant app registrations.</div>:<div className="cred-list">{data.credentialExpiry.items.slice(0,8).map((c,i)=><div key={`${c.appId}-${i}`} className="cred-row"><div><strong>{c.name}</strong><span>{c.type==='certificate'?'Certificate':'Client secret'} • expires {new Date(c.expiresAt).toLocaleDateString()}</span></div><b className={c.daysRemaining<=30?'critical':c.daysRemaining<=90?'warning':''}>{c.daysRemaining<0?'Expired':`${c.daysRemaining}d`}</b></div>)}</div>}<button className="card-link">Read from Application.Read.All; a &lt;30 day badge means rotate now.</button></Card><Card title="Recent Activity" className="activity-card"><table><thead><tr><th>Time</th><th>Activity</th><th>Actor</th><th>Target</th><th>Status</th><th>Risk</th></tr></thead><tbody>{(data.recentSignIns||[]).slice(0,8).map((s,i)=>{const ok=s.status?.errorCode===0;return <tr key={s.id||i}><td>{new Date(s.createdDateTime).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</td><td>{s.isInteractive?'Interactive sign-in':'Sign-in'}</td><td>{s.userDisplayName||s.userPrincipalName||'Service principal'}</td><td>{s.appDisplayName||s.resourceDisplayName||'Microsoft Entra'}</td><td className={ok?'success':'failed'}>{ok?'Success':'Failed'}</td><td className={String(s.riskLevelAggregated||'none').toLowerCase()}>{s.riskLevelAggregated||'none'}</td></tr>})}</tbody></table></Card><Card title="Tenant Evidence"><div className="evidence-list"><div><span>Tenant</span><strong>{data.organization.displayName||'Unknown organization'}</strong></div><div><span>Tenant ID</span><strong className="mono">{data.organization.id||'—'}</strong></div><div><span>Verified domains</span><strong>{data.organization.verifiedDomains?.map(x=>x.name).filter(Boolean).join(', ')||'—'}</strong></div><div><span>Last collection</span><strong>{new Date(data.collectedAt).toLocaleString()}</strong></div><div><span>Conditional Access policies</span><strong>{fmt(data.conditionalAccessPolicies)}</strong></div></div></Card></section>
  </>;
}

function ADDashboard({data}){if(!data)return <div className="empty-state large">Active Directory is selected but the agent has not returned a snapshot.</div>;return <><section className="kpis">{[['AD Users',data.userCount,'♙'],['Enabled Users',data.enabledUserCount,'✓'],['Groups',data.groupCount,'♧'],['Computers',data.computerCount,'▱'],['Domain Controllers',data.domainControllerCount,'◆']].map(([t,v,g])=><div className="kpi" key={t}><div className="kpi-icon">{g}</div><div><div className="kpi-title">{t}</div><div className="kpi-value">{fmt(v)}</div><div className="kpi-change"><span>Live AD Agent query</span></div></div></div>)}</section><section className="grid top-grid"><Card title="AD Identity Hygiene"><div className="ad-metrics"><div><b>{fmt(data.disabledUserCount)}</b><span>Disabled users</span></div><div><b>{fmt(data.staleUserCount)}</b><span>Stale enabled users</span></div><div><b>{fmt(data.usersWithoutManager)}</b><span>Users without manager</span></div><div><b>{fmt(data.privilegedUsers)}</b><span>Privileged users</span></div></div></Card><Card title="Computer Hygiene"><div className="ad-metrics"><div><b>{fmt(data.staleComputerCount)}</b><span>Stale computers</span></div><div><b>{fmt(data.computerCount-data.staleComputerCount)}</b><span>Active recent computers</span></div></div></Card><Card title="Domain Controllers"><div className="dc-list">{(data.domainControllers||[]).map(dc=><div key={dc.HostName}><strong>{dc.HostName}</strong><span>{dc.Site||'Default site'} • {dc.IPv4Address||'no IPv4'} {dc.IsReadOnly?'• RODC':''}</span></div>)}</div></Card></section><section className="bottom-grid"><Card title="Active Directory Source"><div className="evidence-list"><div><span>Domain</span><strong>{data.domain}</strong></div><div><span>Forest</span><strong>{data.forest}</strong></div><div><span>Stale threshold</span><strong>{fmt(data.staleDays)} days</strong></div><div><span>Collected</span><strong>{new Date(data.collectedAt).toLocaleString()}</strong></div></div></Card><Card title="Security Boundary"><div className="empty-state">AD data is collected read-only by the local IAM AD Agent. Entra sign-in and ID Protection metrics remain separate until you switch the source back to Microsoft Entra ID.</div></Card></section></>}

function CombinedDashboard({data,collectorStatus}){
  if(!collectorStatus.connected)return <div className="empty-state large">The multi-tenant collector is not reachable. {collectorStatus.detail}. See <span className="mono">collector/README.md</span> to run it.</div>;
  if(!data)return <div className="empty-state large">Waiting for collector data…</div>;
  const certs=collectorStatus.data?.tenants||[];
  return <>
    <section className="kpis">{[['Tenants',data.tenantCount,'◇'],['Total Users',data.users,'♙'],['Total Applications',data.applications,'▦'],['Risky Users',data.riskyUsers,'♜'],['Privileged Users',data.privilegedUsers,'◈']].map(([t,v,g])=><div className="kpi" key={t}><div className="kpi-icon">{g}</div><div><div className="kpi-title">{t}</div><div className="kpi-value">{fmt(v)}</div><div className="kpi-change"><span>Collector snapshot</span></div></div></div>)}</section>
    <section className="grid top-grid single"><Card title="Per-Tenant Breakdown"><div className="license-table"><table><thead><tr><th>Tenant</th><th>Users</th><th>Applications</th><th>Risky Users</th><th>Privileged Users</th><th>Credentials ≤30d</th><th>Collected</th></tr></thead><tbody>{data.perTenant.map(t=><tr key={t.tenantId}><td>{t.displayName}</td><td>{fmt(t.users)}</td><td>{fmt(t.applications)}</td><td>{fmt(t.riskyUsers)}</td><td>{fmt(t.privilegedUsers)}</td><td>{fmt(t.credentialExpiringSoon)}</td><td>{new Date(t.collectedAt).toLocaleString()}</td></tr>)}</tbody></table></div></Card></section>
    <section className="grid top-grid single"><Card title="Collector Certificate Health"><div className="license-table"><table><thead><tr><th>Tenant</th><th>Certificate expires</th><th>Days remaining</th></tr></thead><tbody>{certs.map(c=><tr key={c.id}><td>{c.displayName}</td><td>{c.certExpiresAt?new Date(c.certExpiresAt).toLocaleDateString():'—'}</td><td className={c.certExpiresInDays!=null&&c.certExpiresInDays<=30?'text-critical':''}>{c.certExpiresInDays!=null?`${c.certExpiresInDays}d`:'—'}</td></tr>)}</tbody></table></div><button className="card-link">The collector's certificate authenticates app-only Graph access. Rotate before 0 remaining days.</button></Card></section>
    <section className="grid top-grid single"><Card title="Application Credentials Expiring ≤30 Days (all tenants)">{!data.credentialExpiry.items.length?<div className="empty-state">No client secrets or certificates expiring soon across configured tenants.</div>:<div className="cred-list">{data.credentialExpiry.items.map((c,i)=><div key={`${c.appId}-${i}`} className="cred-row"><div><strong>{c.name}</strong><span>{c.tenant} • {c.type==='certificate'?'Certificate':'Client secret'} • expires {new Date(c.expiresAt).toLocaleDateString()}</span></div><b className={c.daysRemaining<=30?'critical':'warning'}>{c.daysRemaining<0?'Expired':`${c.daysRemaining}d`}</b></div>)}</div>}</Card></section>
  </>;
}

function DataSourcesPage({sourceId,onSelect,adStatus,collectorStatus}){const iconFor=id=>({entra:'◆',ad:'◇',combined:'⬡',sailpoint:'▣',saviynt:'◎'}[id]||'›');const statusFor=id=>{if(id==='entra')return {connected:true,detail:'Delegated Graph access'};if(id==='ad')return {connected:adStatus.connected,detail:adStatus.connected?'Agent online':'Agent required'};if(id==='combined')return {connected:collectorStatus.connected,detail:collectorStatus.connected?collectorStatus.detail:'Collector required'};return {connected:false,detail:'Connector not configured'};};return <div className="source-page"><div className="source-intro"><div><div className="builder-kicker">DATA SOURCES</div><h2>Identity source control plane</h2><p className="muted">Choose which identity system powers the dashboard. No source is shown as connected unless a live health check succeeds.</p></div></div><div className="source-grid">{DATA_SOURCES.map(s=>{const st=statusFor(s.id);return <button className={`source-card ${sourceId===s.id?'selected':''}`} key={s.id} onClick={()=>onSelect(s.id)}><div className="source-icon">{iconFor(s.id)}</div><div><strong>{s.name}</strong><span>{s.type}</span><small>{st.connected?'Connected • Live':st.detail}</small></div></button>})}</div><div className="agent-box"><h3>Active Directory Agent</h3><p className="muted">Run <span className="mono">agent/IAM-AD-Agent.ps1</span> on a domain-joined Windows host, then set <span className="mono">VITE_AD_AGENT_URL</span>. The dashboard validates <span className="mono">/health</span> before AD data becomes active.</p><div className="agent-status"><Status ok={adStatus.connected} label={adStatus.connected?'Agent online':'Agent unavailable'}/><span>{adStatus.detail}</span></div></div><div className="agent-box"><h3>Multi-Tenant Collector</h3><p className="muted">Run <span className="mono">collector/</span> (certificate-authenticated, on your own infrastructure), then set <span className="mono">VITE_COLLECTOR_URL</span>. Powers the "All Identity Sources" combined view across every configured tenant.</p><div className="agent-status"><Status ok={collectorStatus.connected} label={collectorStatus.connected?'Collector online':'Collector unavailable'}/><span>{collectorStatus.detail}</span></div></div></div>}

function LicensesPage({data,loading,onGrant}){
  if(!data?.licensesAvailable){
    return <div className="source-page"><div className="permission-banner"><div><strong>License permissions are not granted.</strong><span>Grant read-only Organization.Read.All to see purchased, consumed and available seats per Microsoft 365 / Entra license.</span></div><button className="primary" onClick={onGrant}>{loading?'Requesting…':'Grant license permissions'}</button></div>{data&&<div className="empty-state large">{loading?'Loading license data…':'License SKU data unavailable. Grant permission above.'}</div>}</div>;
  }
  return <div className="source-page">
    <section className="kpis">{[['Purchased Seats',data.totalPurchased,'♙'],['Assigned Seats',data.totalConsumed,'✓'],['Available Seats',data.totalAvailable,'◇'],['Stale Licensed Accounts',data.staleLicensedUserCount,'⚠']].map(([t,v,g])=><div className="kpi" key={t}><div className="kpi-icon">{g}</div><div><div className="kpi-title">{t}</div><div className="kpi-value">{fmt(v)}</div><div className="kpi-change"><span>Live Graph query</span></div></div></div>)}</section>
    <section className="grid top-grid single"><Card title={`License Inventory (${fmt(data.skus.length)} SKUs)`}><div className="license-table"><table><thead><tr><th>License</th><th>SKU code</th><th>Purchased</th><th>Assigned</th><th>Available</th><th>Utilization</th></tr></thead><tbody>{data.skus.map(s=><tr key={s.skuId}><td>{s.name}</td><td className="mono">{s.skuPartNumber}</td><td>{fmt(s.purchased)}</td><td>{fmt(s.consumed)}</td><td>{fmt(s.available)}</td><td>{pct(s.consumed,s.purchased)}</td></tr>)}</tbody></table></div></Card></section>
    <section className="grid top-grid single"><Card title="Recommendations">{(()=>{const recs=[...data.skus.filter(s=>s.purchased>0&&s.available>0&&(s.consumed/s.purchased)<0.8).map(s=>({t:`${fmt(s.available)} unused ${s.name} seats`,d:`Only ${pct(s.consumed,s.purchased)} of purchased seats are assigned. Consider reallocating or reducing the purchase.`})),...(data.staleLicensedUserCount?[{t:`${fmt(data.staleLicensedUserCount)} licensed accounts inactive 90+ days`,d:'These accounts hold at least one license but have no recent sign-in. Review for license reclamation.'}]:[])];return recs.length?recs.map((r,i)=><div className="ai-item" key={i}><div className="ai-icon amber">✦</div><div className="ai-copy"><strong>{r.t}</strong><span>{r.d}</span></div></div>):<div className="empty-state">No license optimization findings from the current data.</div>;})()}</Card></section>
    {data.staleLicensedUserCount>0&&<section className="grid top-grid single"><Card title="Stale Licensed Accounts"><div className="license-table"><table><thead><tr><th>User</th><th>UPN</th><th>Last sign-in</th></tr></thead><tbody>{data.staleLicensedUsers.map(u=><tr key={u.upn}><td>{u.name}</td><td>{u.upn}</td><td>{u.lastSignIn?new Date(u.lastSignIn).toLocaleDateString():'Never observed'}</td></tr>)}</tbody></table></div></Card></section>}
  </div>;
}

function App(){
  const [active,setActive]=useState('Overview');const [sourceId,setSourceId]=useState(getActiveSource());const [data,setData]=useState(window.__IAM_SNAPSHOT__||null);const [sourceData,setSourceData]=useState(null);const [loading,setLoading]=useState(!window.__IAM_SNAPSHOT__);const [toast,setToast]=useState('');const [adStatus,setAdStatus]=useState({configured:false,connected:false,detail:'Checking…'});const [licenseData,setLicenseData]=useState(null);const [licenseLoading,setLicenseLoading]=useState(false);const [collectorStatus,setCollectorStatus]=useState({configured:false,connected:false,detail:'Checking…'});const [combinedData,setCombinedData]=useState(null);
  useEffect(()=>{const h=e=>{setData(e.detail);setLoading(false)};document.addEventListener('iam-live-data',h);return()=>document.removeEventListener('iam-live-data',h)},[]);
  useEffect(()=>{checkAdAgent().then(setAdStatus)},[]);
  useEffect(()=>{checkCollector().then(setCollectorStatus)},[]);
  useEffect(()=>{if(sourceId==='ad'&&adStatus.connected){setLoading(true);getAdSnapshot().then(x=>{setSourceData(x);setLoading(false)}).catch(e=>{setSourceData(null);setLoading(false);setToast(e.message)})}else if(sourceId!=='ad')setSourceData(null)},[sourceId,adStatus.connected]);
  useEffect(()=>{if(sourceId==='combined'&&collectorStatus.connected){setLoading(true);getCombinedSnapshot().then(x=>{setCombinedData(x);setLoading(false)}).catch(e=>{setCombinedData(null);setLoading(false);setToast(e.message)})}else if(sourceId!=='combined')setCombinedData(null)},[sourceId,collectorStatus.connected]);
  useEffect(()=>{if(active==='Licenses'&&!licenseData&&!licenseLoading){setLicenseLoading(true);getLicenseSnapshot().then(d=>{setLicenseData(d);setLicenseLoading(false)}).catch(e=>{setLicenseLoading(false);setToast(e.message||'License data unavailable')})}},[active]);
  const refreshingRef=useRef(false);
  useEffect(()=>{
    if(sourceId!=='entra')return;
    const id=setInterval(async()=>{
      if(refreshingRef.current||document.visibilityState!=='visible')return;
      refreshingRef.current=true;
      try{const snap=await syncLiveTenantData();setData(snap);}catch(e){console.error('IAM auto-refresh failed:',e);}
      finally{refreshingRef.current=false;}
    },REFRESH_SECONDS*1000);
    return()=>clearInterval(id);
  },[sourceId]);
  const refresh=async()=>{setLoading(true);try{if(sourceId==='entra'){const snap=await syncLiveTenantData();setData(snap);setToast('Entra data refreshed')}else if(sourceId==='ad'){const snap=await getAdSnapshot();setSourceData(snap);setToast('AD data refreshed')}else if(sourceId==='combined'){const snap=await getCombinedSnapshot();setCombinedData(snap);setToast('Combined data refreshed')}else setToast(`${sourceById(sourceId).name} is not configured`)}catch(e){setToast(e.message||'Refresh failed')}finally{setLoading(false);setTimeout(()=>setToast(''),3000)}};
  const chooseSource=id=>{setActiveSource(id);setSourceId(id);setActive('Overview');};
  const grantSecurity=async()=>{try{setToast('Requesting security permissions…');await connectSecurityScopes();setToast('Consent completed; refreshing security data…');await refresh()}catch(e){setToast(e.message||'Security consent failed')}setTimeout(()=>setToast(''),4000)};
  const grantLicense=async()=>{setLicenseLoading(true);try{setToast('Requesting license permissions…');await connectLicenseScopes();setToast('Consent completed; loading license data…');const d=await getLicenseSnapshot();setLicenseData(d);}catch(e){setToast(e.message||'License consent failed')}finally{setLicenseLoading(false);setTimeout(()=>setToast(''),4000)}};
  const title=active==='Licenses'?'Licenses':sourceId==='entra'?(active==='Overview'?'Executive Overview':active):sourceId==='ad'?(active==='Overview'?'Active Directory Overview':active):sourceById(sourceId).name;
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><span>◆</span></div><div><div className="brand-name">IAM Intelligence</div><div className="brand-tag">Identity. Secure. Simplified.</div></div></div><nav>{nav.map(([label,glyph])=>label.startsWith('__')?<div className="section-label" key={label}>{label.slice(2)}</div>:<button key={label} className={`nav-item ${active===label?'active':''}`} onClick={()=>setActive(label)}><Icon>{glyph}</Icon><span>{label}</span></button>)}</nav><div className="sidebar-footer">Source<br/><strong>{sourceById(sourceId).name}</strong></div></aside><main className="main"><header className="topbar"><div className="page-title"><span>{title}</span><span className="chevron">⌄</span></div><div className="top-actions"><div className="source-tabs">{DATA_SOURCES.map(s=><button key={s.id} className={`source-tab ${sourceId===s.id?'active':''}`} onClick={()=>chooseSource(s.id)} title={s.type}>{s.name}</button>)}</div><Status ok={sourceId==='entra'||(sourceId==='ad'&&adStatus.connected)} label="Live"/><button className="icon-btn" onClick={refresh} title="Refresh">↻</button><button className="icon-btn labeled" onClick={signOut}><span>⇥</span>Sign out</button><button className="filter-btn" onClick={()=>setActive('Data Sources')}>Data Sources</button></div></header><div className="content"><div className="live-row"><span className="live-dot"></span> Source: <strong>{sourceById(sourceId).name}</strong><span className="separator">•</span>{sourceId==='entra'?`Tenant: ${data?.organization?.displayName||'Loading…'}`:sourceId==='ad'?`Domain: ${sourceData?.domain||'Loading…'}`:sourceId==='combined'?`${combinedData?.tenantCount??'…'} tenant(s) via collector`:'Connector not configured'}<span className="separator">•</span>{loading?'Collecting live data…':`Last refresh ${data?.collectedAt?new Date(data.collectedAt).toLocaleTimeString():sourceData?.collectedAt?new Date(sourceData.collectedAt).toLocaleTimeString():combinedData?.collectedAt?new Date(combinedData.collectedAt).toLocaleTimeString():'—'}`}{sourceId==='entra'&&<><span className="separator">•</span>Auto-refresh every {REFRESH_SECONDS}s</>}</div>{active==='Data Sources'?<DataSourcesPage sourceId={sourceId} onSelect={chooseSource} adStatus={adStatus} collectorStatus={collectorStatus}/>:active==='Licenses'?<LicensesPage data={licenseData} loading={licenseLoading} onGrant={grantLicense}/>:sourceId==='entra'&&data?<EntraDashboard data={data} onSecurity={grantSecurity}/>:sourceId==='ad'?<ADDashboard data={sourceData}/>:sourceId==='combined'?<CombinedDashboard data={combinedData} collectorStatus={collectorStatus}/>:<div className="empty-state large">{sourceById(sourceId).name} connector is not configured. Open Data Sources to configure it.</div>}</div></main>{toast&&<div className="toast">✓ {toast}</div>}</div>;
}

createRoot(document.getElementById('root')).render(<App/>);
